/*
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.onemsg.sdk.model;

import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.onemsg.sdk.ApiClient;
/**
 * CallingSettingsCallingSipServersInner
 */
@JsonPropertyOrder({
  CallingSettingsCallingSipServersInner.JSON_PROPERTY_HOSTNAME,
  CallingSettingsCallingSipServersInner.JSON_PROPERTY_PORT,
  CallingSettingsCallingSipServersInner.JSON_PROPERTY_REQUEST_URI_USER_PARAMS,
  CallingSettingsCallingSipServersInner.JSON_PROPERTY_SIP_USER_PASSWORD,
  CallingSettingsCallingSipServersInner.JSON_PROPERTY_PASSWORD,
  CallingSettingsCallingSipServersInner.JSON_PROPERTY_APP_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-20T11:31:39.159231868+02:00[Europe/Berlin]", comments = "Generator version: 7.22.0")
public class CallingSettingsCallingSipServersInner {
  public static final String JSON_PROPERTY_HOSTNAME = "hostname";
  @javax.annotation.Nullable
  private String hostname;

  public static final String JSON_PROPERTY_PORT = "port";
  @javax.annotation.Nullable
  private Integer port;

  public static final String JSON_PROPERTY_REQUEST_URI_USER_PARAMS = "request_uri_user_params";
  @javax.annotation.Nullable
  private Map<String, String> requestUriUserParams = new HashMap<>();

  public static final String JSON_PROPERTY_SIP_USER_PASSWORD = "sip_user_password";
  @javax.annotation.Nullable
  private String sipUserPassword;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  @javax.annotation.Nullable
  private String password;

  public static final String JSON_PROPERTY_APP_ID = "app_id";
  @javax.annotation.Nullable
  private String appId;

  public CallingSettingsCallingSipServersInner() { 
  }

  public CallingSettingsCallingSipServersInner hostname(@javax.annotation.Nullable String hostname) {
    this.hostname = hostname;
    return this;
  }

  /**
   * Get hostname
   * @return hostname
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HOSTNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHostname() {
    return hostname;
  }


  @JsonProperty(value = JSON_PROPERTY_HOSTNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHostname(@javax.annotation.Nullable String hostname) {
    this.hostname = hostname;
  }


  public CallingSettingsCallingSipServersInner port(@javax.annotation.Nullable Integer port) {
    this.port = port;
    return this;
  }

  /**
   * Get port
   * @return port
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getPort() {
    return port;
  }


  @JsonProperty(value = JSON_PROPERTY_PORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPort(@javax.annotation.Nullable Integer port) {
    this.port = port;
  }


  public CallingSettingsCallingSipServersInner requestUriUserParams(@javax.annotation.Nullable Map<String, String> requestUriUserParams) {
    this.requestUriUserParams = requestUriUserParams;
    return this;
  }

  public CallingSettingsCallingSipServersInner putRequestUriUserParamsItem(String key, String requestUriUserParamsItem) {
    if (this.requestUriUserParams == null) {
      this.requestUriUserParams = new HashMap<>();
    }
    this.requestUriUserParams.put(key, requestUriUserParamsItem);
    return this;
  }

  /**
   * Get requestUriUserParams
   * @return requestUriUserParams
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REQUEST_URI_USER_PARAMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, String> getRequestUriUserParams() {
    return requestUriUserParams;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_URI_USER_PARAMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestUriUserParams(@javax.annotation.Nullable Map<String, String> requestUriUserParams) {
    this.requestUriUserParams = requestUriUserParams;
  }


  public CallingSettingsCallingSipServersInner sipUserPassword(@javax.annotation.Nullable String sipUserPassword) {
    this.sipUserPassword = sipUserPassword;
    return this;
  }

  /**
   * Present on GET when SIP credentials are returned by Meta
   * @return sipUserPassword
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SIP_USER_PASSWORD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSipUserPassword() {
    return sipUserPassword;
  }


  @JsonProperty(value = JSON_PROPERTY_SIP_USER_PASSWORD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSipUserPassword(@javax.annotation.Nullable String sipUserPassword) {
    this.sipUserPassword = sipUserPassword;
  }


  public CallingSettingsCallingSipServersInner password(@javax.annotation.Nullable String password) {
    this.password = password;
    return this;
  }

  /**
   * Alternate password field name from some Meta responses
   * @return password
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PASSWORD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPassword() {
    return password;
  }


  @JsonProperty(value = JSON_PROPERTY_PASSWORD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassword(@javax.annotation.Nullable String password) {
    this.password = password;
  }


  public CallingSettingsCallingSipServersInner appId(@javax.annotation.Nullable String appId) {
    this.appId = appId;
    return this;
  }

  /**
   * Get appId
   * @return appId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_APP_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAppId() {
    return appId;
  }


  @JsonProperty(value = JSON_PROPERTY_APP_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppId(@javax.annotation.Nullable String appId) {
    this.appId = appId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   * @param key the name of the property
   * @param value the value of the property
   * @return self reference
   */
  @JsonAnySetter
  public CallingSettingsCallingSipServersInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) properties.
   * @return the additional (undeclared) properties
   */
  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   * @param key the name of the property
   * @return the additional (undeclared) property with the specified name
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }

  /**
   * Return true if this CallingSettings_calling_sip_servers_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CallingSettingsCallingSipServersInner callingSettingsCallingSipServersInner = (CallingSettingsCallingSipServersInner) o;
    return Objects.equals(this.hostname, callingSettingsCallingSipServersInner.hostname) &&
        Objects.equals(this.port, callingSettingsCallingSipServersInner.port) &&
        Objects.equals(this.requestUriUserParams, callingSettingsCallingSipServersInner.requestUriUserParams) &&
        Objects.equals(this.sipUserPassword, callingSettingsCallingSipServersInner.sipUserPassword) &&
        Objects.equals(this.password, callingSettingsCallingSipServersInner.password) &&
        Objects.equals(this.appId, callingSettingsCallingSipServersInner.appId)&&
        Objects.equals(this.additionalProperties, callingSettingsCallingSipServersInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hostname, port, requestUriUserParams, sipUserPassword, password, appId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CallingSettingsCallingSipServersInner {\n");
    sb.append("    hostname: ").append(toIndentedString(hostname)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    requestUriUserParams: ").append(toIndentedString(requestUriUserParams)).append("\n");
    sb.append("    sipUserPassword: ").append(toIndentedString(sipUserPassword)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `hostname` to the URL query string
    if (getHostname() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shostname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHostname()))));
    }

    // add `port` to the URL query string
    if (getPort() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sport%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPort()))));
    }

    // add `request_uri_user_params` to the URL query string
    if (getRequestUriUserParams() != null) {
      for (String _key : getRequestUriUserParams().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%srequest_uri_user_params%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getRequestUriUserParams().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getRequestUriUserParams().get(_key)))));
      }
    }

    // add `sip_user_password` to the URL query string
    if (getSipUserPassword() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssip_user_password%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSipUserPassword()))));
    }

    // add `password` to the URL query string
    if (getPassword() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spassword%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPassword()))));
    }

    // add `app_id` to the URL query string
    if (getAppId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sapp_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAppId()))));
    }

    return joiner.toString();
  }
}

