/*
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.onemsg.sdk.model;

import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.onemsg.sdk.model.ConversationalAutomationCommandsInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.onemsg.sdk.ApiClient;
/**
 * ConversationalAutomation
 */
@JsonPropertyOrder({
  ConversationalAutomation.JSON_PROPERTY_ENABLE_WELCOME_MESSAGE,
  ConversationalAutomation.JSON_PROPERTY_PROMPTS,
  ConversationalAutomation.JSON_PROPERTY_COMMANDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-24T12:33:30.009264922Z[Etc/UTC]", comments = "Generator version: 7.22.0")
public class ConversationalAutomation {
  public static final String JSON_PROPERTY_ENABLE_WELCOME_MESSAGE = "enable_welcome_message";
  @javax.annotation.Nullable
  private Boolean enableWelcomeMessage;

  public static final String JSON_PROPERTY_PROMPTS = "prompts";
  @javax.annotation.Nullable
  private List<String> prompts = new ArrayList<>();

  public static final String JSON_PROPERTY_COMMANDS = "commands";
  @javax.annotation.Nullable
  private List<ConversationalAutomationCommandsInner> commands = new ArrayList<>();

  public ConversationalAutomation() { 
  }

  public ConversationalAutomation enableWelcomeMessage(@javax.annotation.Nullable Boolean enableWelcomeMessage) {
    this.enableWelcomeMessage = enableWelcomeMessage;
    return this;
  }

  /**
   * Enable the automatic welcome message for new conversations
   * @return enableWelcomeMessage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENABLE_WELCOME_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEnableWelcomeMessage() {
    return enableWelcomeMessage;
  }


  @JsonProperty(value = JSON_PROPERTY_ENABLE_WELCOME_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnableWelcomeMessage(@javax.annotation.Nullable Boolean enableWelcomeMessage) {
    this.enableWelcomeMessage = enableWelcomeMessage;
  }


  public ConversationalAutomation prompts(@javax.annotation.Nullable List<String> prompts) {
    this.prompts = prompts;
    return this;
  }

  public ConversationalAutomation addPromptsItem(String promptsItem) {
    if (this.prompts == null) {
      this.prompts = new ArrayList<>();
    }
    this.prompts.add(promptsItem);
    return this;
  }

  /**
   * Ice-breaker prompt strings (max 4, each ≤ 80 characters)
   * @return prompts
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROMPTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getPrompts() {
    return prompts;
  }


  @JsonProperty(value = JSON_PROPERTY_PROMPTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrompts(@javax.annotation.Nullable List<String> prompts) {
    this.prompts = prompts;
  }


  public ConversationalAutomation commands(@javax.annotation.Nullable List<ConversationalAutomationCommandsInner> commands) {
    this.commands = commands;
    return this;
  }

  public ConversationalAutomation addCommandsItem(ConversationalAutomationCommandsInner commandsItem) {
    if (this.commands == null) {
      this.commands = new ArrayList<>();
    }
    this.commands.add(commandsItem);
    return this;
  }

  /**
   * Slash commands shown in WhatsApp
   * @return commands
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMMANDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<ConversationalAutomationCommandsInner> getCommands() {
    return commands;
  }


  @JsonProperty(value = JSON_PROPERTY_COMMANDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommands(@javax.annotation.Nullable List<ConversationalAutomationCommandsInner> commands) {
    this.commands = commands;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   * @param key the name of the property
   * @param value the value of the property
   * @return self reference
   */
  @JsonAnySetter
  public ConversationalAutomation putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) properties.
   * @return the additional (undeclared) properties
   */
  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   * @param key the name of the property
   * @return the additional (undeclared) property with the specified name
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }

  /**
   * Return true if this ConversationalAutomation object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversationalAutomation conversationalAutomation = (ConversationalAutomation) o;
    return Objects.equals(this.enableWelcomeMessage, conversationalAutomation.enableWelcomeMessage) &&
        Objects.equals(this.prompts, conversationalAutomation.prompts) &&
        Objects.equals(this.commands, conversationalAutomation.commands)&&
        Objects.equals(this.additionalProperties, conversationalAutomation.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enableWelcomeMessage, prompts, commands, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversationalAutomation {\n");
    sb.append("    enableWelcomeMessage: ").append(toIndentedString(enableWelcomeMessage)).append("\n");
    sb.append("    prompts: ").append(toIndentedString(prompts)).append("\n");
    sb.append("    commands: ").append(toIndentedString(commands)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `enable_welcome_message` to the URL query string
    if (getEnableWelcomeMessage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%senable_welcome_message%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEnableWelcomeMessage()))));
    }

    // add `prompts` to the URL query string
    if (getPrompts() != null) {
      for (int i = 0; i < getPrompts().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sprompts%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getPrompts().get(i)))));
      }
    }

    // add `commands` to the URL query string
    if (getCommands() != null) {
      for (int i = 0; i < getCommands().size(); i++) {
        if (getCommands().get(i) != null) {
          joiner.add(String.format(java.util.Locale.ROOT, "%scommands%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
              ApiClient.urlEncode(ApiClient.valueToString(getCommands().get(i)))));
        }
      }
    }

    return joiner.toString();
  }
}

