/*
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.onemsg.sdk.model;

import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.onemsg.sdk.model.InitiateCallRequestSession;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.onemsg.sdk.ApiClient;
/**
 * Call action payload for &#x60;POST /initiateCall&#x60; (proxies upstream &#x60;POST /calling/calls&#x60;).  Despite the path name, this endpoint handles **all** call actions — not only outbound connect.  ## Required fields by &#x60;action&#x60;  | action | Required | &#x60;session&#x60; | |--------|----------|-----------| | &#x60;connect&#x60; (outbound) | &#x60;messaging_product&#x60;, &#x60;to&#x60;, &#x60;action&#x60; | &#x60;sdp_type: offer&#x60; + business WebRTC SDP | | &#x60;pre_accept&#x60; | &#x60;messaging_product&#x60;, &#x60;call_id&#x60;, &#x60;action&#x60; | &#x60;sdp_type: answer&#x60; (WebRTC-generated) | | &#x60;accept&#x60; | &#x60;messaging_product&#x60;, &#x60;call_id&#x60;, &#x60;action&#x60; | &#x60;sdp_type: answer&#x60; (WebRTC-generated) | | &#x60;reject&#x60; | &#x60;messaging_product&#x60;, &#x60;call_id&#x60;, &#x60;action&#x60; | none | | &#x60;terminate&#x60; | &#x60;messaging_product&#x60;, &#x60;call_id&#x60;, &#x60;action&#x60; | none |  **Critical:** For &#x60;pre_accept&#x60; / &#x60;accept&#x60;, &#x60;session.sdp&#x60; must be a **WebRTC-generated SDP answer**. Do not echo Meta&#39;s offer SDP back. Postman alone cannot establish real media — you need a WebRTC (or SIP) stack. 
 */
@JsonPropertyOrder({
  InitiateCallRequest.JSON_PROPERTY_MESSAGING_PRODUCT,
  InitiateCallRequest.JSON_PROPERTY_ACTION,
  InitiateCallRequest.JSON_PROPERTY_CALL_ID,
  InitiateCallRequest.JSON_PROPERTY_TO,
  InitiateCallRequest.JSON_PROPERTY_BIZ_OPAQUE_CALLBACK_DATA,
  InitiateCallRequest.JSON_PROPERTY_SESSION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-20T11:31:39.159231868+02:00[Europe/Berlin]", comments = "Generator version: 7.22.0")
public class InitiateCallRequest {
  /**
   * Must be &#x60;whatsapp&#x60;
   */
  public enum MessagingProductEnum {
    WHATSAPP(String.valueOf("whatsapp"));

    private String value;

    MessagingProductEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MessagingProductEnum fromValue(String value) {
      for (MessagingProductEnum b : MessagingProductEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MESSAGING_PRODUCT = "messaging_product";
  @javax.annotation.Nonnull
  private MessagingProductEnum messagingProduct;

  /**
   * Call control action
   */
  public enum ActionEnum {
    CONNECT(String.valueOf("connect")),
    
    PRE_ACCEPT(String.valueOf("pre_accept")),
    
    ACCEPT(String.valueOf("accept")),
    
    REJECT(String.valueOf("reject")),
    
    TERMINATE(String.valueOf("terminate"));

    private String value;

    ActionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActionEnum fromValue(String value) {
      for (ActionEnum b : ActionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACTION = "action";
  @javax.annotation.Nonnull
  private ActionEnum action;

  public static final String JSON_PROPERTY_CALL_ID = "call_id";
  @javax.annotation.Nullable
  private String callId;

  public static final String JSON_PROPERTY_TO = "to";
  @javax.annotation.Nullable
  private String to;

  public static final String JSON_PROPERTY_BIZ_OPAQUE_CALLBACK_DATA = "biz_opaque_callback_data";
  @javax.annotation.Nullable
  private String bizOpaqueCallbackData;

  public static final String JSON_PROPERTY_SESSION = "session";
  @javax.annotation.Nullable
  private InitiateCallRequestSession session;

  public InitiateCallRequest() { 
  }

  public InitiateCallRequest messagingProduct(@javax.annotation.Nonnull MessagingProductEnum messagingProduct) {
    this.messagingProduct = messagingProduct;
    return this;
  }

  /**
   * Must be &#x60;whatsapp&#x60;
   * @return messagingProduct
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGING_PRODUCT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public MessagingProductEnum getMessagingProduct() {
    return messagingProduct;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGING_PRODUCT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessagingProduct(@javax.annotation.Nonnull MessagingProductEnum messagingProduct) {
    this.messagingProduct = messagingProduct;
  }


  public InitiateCallRequest action(@javax.annotation.Nonnull ActionEnum action) {
    this.action = action;
    return this;
  }

  /**
   * Call control action
   * @return action
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ActionEnum getAction() {
    return action;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAction(@javax.annotation.Nonnull ActionEnum action) {
    this.action = action;
  }


  public InitiateCallRequest callId(@javax.annotation.Nullable String callId) {
    this.callId = callId;
    return this;
  }

  /**
   * WhatsApp call id from the inbound/outbound calls webhook (&#x60;calls[].id&#x60;). Required for &#x60;pre_accept&#x60;, &#x60;accept&#x60;, &#x60;reject&#x60;, &#x60;terminate&#x60;. 
   * @return callId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CALL_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCallId() {
    return callId;
  }


  @JsonProperty(value = JSON_PROPERTY_CALL_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCallId(@javax.annotation.Nullable String callId) {
    this.callId = callId;
  }


  public InitiateCallRequest to(@javax.annotation.Nullable String to) {
    this.to = to;
    return this;
  }

  /**
   * Recipient WhatsApp user phone (digits, country code, no +). Required for outbound &#x60;connect&#x60;. 
   * @return to
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTo() {
    return to;
  }


  @JsonProperty(value = JSON_PROPERTY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTo(@javax.annotation.Nullable String to) {
    this.to = to;
  }


  public InitiateCallRequest bizOpaqueCallbackData(@javax.annotation.Nullable String bizOpaqueCallbackData) {
    this.bizOpaqueCallbackData = bizOpaqueCallbackData;
    return this;
  }

  /**
   * Optional opaque string echoed on later call webhooks for correlation
   * @return bizOpaqueCallbackData
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BIZ_OPAQUE_CALLBACK_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBizOpaqueCallbackData() {
    return bizOpaqueCallbackData;
  }


  @JsonProperty(value = JSON_PROPERTY_BIZ_OPAQUE_CALLBACK_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBizOpaqueCallbackData(@javax.annotation.Nullable String bizOpaqueCallbackData) {
    this.bizOpaqueCallbackData = bizOpaqueCallbackData;
  }


  public InitiateCallRequest session(@javax.annotation.Nullable InitiateCallRequestSession session) {
    this.session = session;
    return this;
  }

  /**
   * Get session
   * @return session
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SESSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public InitiateCallRequestSession getSession() {
    return session;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSession(@javax.annotation.Nullable InitiateCallRequestSession session) {
    this.session = session;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   * @param key the name of the property
   * @param value the value of the property
   * @return self reference
   */
  @JsonAnySetter
  public InitiateCallRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) properties.
   * @return the additional (undeclared) properties
   */
  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   * @param key the name of the property
   * @return the additional (undeclared) property with the specified name
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }

  /**
   * Return true if this InitiateCallRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InitiateCallRequest initiateCallRequest = (InitiateCallRequest) o;
    return Objects.equals(this.messagingProduct, initiateCallRequest.messagingProduct) &&
        Objects.equals(this.action, initiateCallRequest.action) &&
        Objects.equals(this.callId, initiateCallRequest.callId) &&
        Objects.equals(this.to, initiateCallRequest.to) &&
        Objects.equals(this.bizOpaqueCallbackData, initiateCallRequest.bizOpaqueCallbackData) &&
        Objects.equals(this.session, initiateCallRequest.session)&&
        Objects.equals(this.additionalProperties, initiateCallRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messagingProduct, action, callId, to, bizOpaqueCallbackData, session, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InitiateCallRequest {\n");
    sb.append("    messagingProduct: ").append(toIndentedString(messagingProduct)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    callId: ").append(toIndentedString(callId)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    bizOpaqueCallbackData: ").append(toIndentedString(bizOpaqueCallbackData)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `messaging_product` to the URL query string
    if (getMessagingProduct() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smessaging_product%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMessagingProduct()))));
    }

    // add `action` to the URL query string
    if (getAction() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saction%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAction()))));
    }

    // add `call_id` to the URL query string
    if (getCallId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scall_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCallId()))));
    }

    // add `to` to the URL query string
    if (getTo() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sto%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTo()))));
    }

    // add `biz_opaque_callback_data` to the URL query string
    if (getBizOpaqueCallbackData() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbiz_opaque_callback_data%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBizOpaqueCallbackData()))));
    }

    // add `session` to the URL query string
    if (getSession() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssession%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSession()))));
    }

    return joiner.toString();
  }
}

