/*
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.onemsg.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.onemsg.sdk.model.SendListRequestSectionsInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.onemsg.sdk.ApiClient;
/**
 * SendListRequest
 */
@JsonPropertyOrder({
  SendListRequest.JSON_PROPERTY_PHONE,
  SendListRequest.JSON_PROPERTY_BODY,
  SendListRequest.JSON_PROPERTY_BUTTON_TEXT,
  SendListRequest.JSON_PROPERTY_ACTION,
  SendListRequest.JSON_PROPERTY_SECTIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-24T12:33:30.009264922Z[Etc/UTC]", comments = "Generator version: 7.22.0")
public class SendListRequest {
  public static final String JSON_PROPERTY_PHONE = "phone";
  @javax.annotation.Nullable
  private String phone;

  public static final String JSON_PROPERTY_BODY = "body";
  @javax.annotation.Nullable
  private String body;

  public static final String JSON_PROPERTY_BUTTON_TEXT = "buttonText";
  @javax.annotation.Nullable
  private String buttonText;

  public static final String JSON_PROPERTY_ACTION = "action";
  @javax.annotation.Nullable
  private String action;

  public static final String JSON_PROPERTY_SECTIONS = "sections";
  @javax.annotation.Nullable
  private List<SendListRequestSectionsInner> sections = new ArrayList<>();

  public SendListRequest() { 
  }

  public SendListRequest phone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
    return this;
  }

  /**
   * Get phone
   * @return phone
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PHONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPhone() {
    return phone;
  }


  @JsonProperty(value = JSON_PROPERTY_PHONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
  }


  public SendListRequest body(@javax.annotation.Nullable String body) {
    this.body = body;
    return this;
  }

  /**
   * Get body
   * @return body
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBody() {
    return body;
  }


  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBody(@javax.annotation.Nullable String body) {
    this.body = body;
  }


  public SendListRequest buttonText(@javax.annotation.Nullable String buttonText) {
    this.buttonText = buttonText;
    return this;
  }

  /**
   * Get buttonText
   * @return buttonText
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BUTTON_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getButtonText() {
    return buttonText;
  }


  @JsonProperty(value = JSON_PROPERTY_BUTTON_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setButtonText(@javax.annotation.Nullable String buttonText) {
    this.buttonText = buttonText;
  }


  public SendListRequest action(@javax.annotation.Nullable String action) {
    this.action = action;
    return this;
  }

  /**
   * Get action
   * @return action
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAction() {
    return action;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAction(@javax.annotation.Nullable String action) {
    this.action = action;
  }


  public SendListRequest sections(@javax.annotation.Nullable List<SendListRequestSectionsInner> sections) {
    this.sections = sections;
    return this;
  }

  public SendListRequest addSectionsItem(SendListRequestSectionsInner sectionsItem) {
    if (this.sections == null) {
      this.sections = new ArrayList<>();
    }
    this.sections.add(sectionsItem);
    return this;
  }

  /**
   * Get sections
   * @return sections
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<SendListRequestSectionsInner> getSections() {
    return sections;
  }


  @JsonProperty(value = JSON_PROPERTY_SECTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSections(@javax.annotation.Nullable List<SendListRequestSectionsInner> sections) {
    this.sections = sections;
  }


  /**
   * Return true if this sendList_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendListRequest sendListRequest = (SendListRequest) o;
    return Objects.equals(this.phone, sendListRequest.phone) &&
        Objects.equals(this.body, sendListRequest.body) &&
        Objects.equals(this.buttonText, sendListRequest.buttonText) &&
        Objects.equals(this.action, sendListRequest.action) &&
        Objects.equals(this.sections, sendListRequest.sections);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phone, body, buttonText, action, sections);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendListRequest {\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    buttonText: ").append(toIndentedString(buttonText)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    sections: ").append(toIndentedString(sections)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `phone` to the URL query string
    if (getPhone() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sphone%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPhone()))));
    }

    // add `body` to the URL query string
    if (getBody() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbody%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBody()))));
    }

    // add `buttonText` to the URL query string
    if (getButtonText() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbuttonText%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getButtonText()))));
    }

    // add `action` to the URL query string
    if (getAction() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saction%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAction()))));
    }

    // add `sections` to the URL query string
    if (getSections() != null) {
      for (int i = 0; i < getSections().size(); i++) {
        if (getSections().get(i) != null) {
          joiner.add(getSections().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%ssections%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

