/*
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.onemsg.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.onemsg.sdk.model.SendFlowRequest1Header;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.onemsg.sdk.ApiClient;
/**
 * SendFlowRequest1
 */
@JsonPropertyOrder({
  SendFlowRequest1.JSON_PROPERTY_BODY,
  SendFlowRequest1.JSON_PROPERTY_HEADER,
  SendFlowRequest1.JSON_PROPERTY_FOOTER,
  SendFlowRequest1.JSON_PROPERTY_FLOW_ID,
  SendFlowRequest1.JSON_PROPERTY_FLOW_TOKEN,
  SendFlowRequest1.JSON_PROPERTY_FLOW_CTA,
  SendFlowRequest1.JSON_PROPERTY_FLOW_ACTION,
  SendFlowRequest1.JSON_PROPERTY_FLOW_ACTION_PAYLOAD,
  SendFlowRequest1.JSON_PROPERTY_FLOW_MESSAGE_VERSION,
  SendFlowRequest1.JSON_PROPERTY_MODE,
  SendFlowRequest1.JSON_PROPERTY_FLOW_ACTION_DATA,
  SendFlowRequest1.JSON_PROPERTY_FLOW_ACTION_SCREEN,
  SendFlowRequest1.JSON_PROPERTY_QUOTED_MSG_ID,
  SendFlowRequest1.JSON_PROPERTY_CHAT_ID,
  SendFlowRequest1.JSON_PROPERTY_PHONE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-17T12:18:29.623765636Z[Etc/UTC]", comments = "Generator version: 7.22.0")
public class SendFlowRequest1 {
  public static final String JSON_PROPERTY_BODY = "body";
  @javax.annotation.Nonnull
  private String body;

  public static final String JSON_PROPERTY_HEADER = "header";
  @javax.annotation.Nullable
  private SendFlowRequest1Header header;

  public static final String JSON_PROPERTY_FOOTER = "footer";
  @javax.annotation.Nullable
  private String footer;

  public static final String JSON_PROPERTY_FLOW_ID = "flowId";
  @javax.annotation.Nonnull
  private String flowId;

  public static final String JSON_PROPERTY_FLOW_TOKEN = "flowToken";
  @javax.annotation.Nonnull
  private String flowToken;

  public static final String JSON_PROPERTY_FLOW_CTA = "flowCta";
  @javax.annotation.Nonnull
  private String flowCta;

  /**
   * Gets or Sets flowAction
   */
  public enum FlowActionEnum {
    NAVIGATE(String.valueOf("navigate")),
    
    DATA_EXCHANGE(String.valueOf("data_exchange"));

    private String value;

    FlowActionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FlowActionEnum fromValue(String value) {
      for (FlowActionEnum b : FlowActionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FLOW_ACTION = "flowAction";
  @javax.annotation.Nullable
  private FlowActionEnum flowAction;

  public static final String JSON_PROPERTY_FLOW_ACTION_PAYLOAD = "flowActionPayload";
  @javax.annotation.Nullable
  private Object flowActionPayload;

  public static final String JSON_PROPERTY_FLOW_MESSAGE_VERSION = "flowMessageVersion";
  @javax.annotation.Nullable
  private String flowMessageVersion;

  /**
   * Gets or Sets mode
   */
  public enum ModeEnum {
    DRAFT(String.valueOf("draft")),
    
    PUBLISHED(String.valueOf("published"));

    private String value;

    ModeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ModeEnum fromValue(String value) {
      for (ModeEnum b : ModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MODE = "mode";
  @javax.annotation.Nullable
  private ModeEnum mode;

  public static final String JSON_PROPERTY_FLOW_ACTION_DATA = "flowActionData";
  @javax.annotation.Nullable
  private Object flowActionData;

  public static final String JSON_PROPERTY_FLOW_ACTION_SCREEN = "flowActionScreen";
  @javax.annotation.Nullable
  private String flowActionScreen;

  public static final String JSON_PROPERTY_QUOTED_MSG_ID = "quotedMsgId";
  @javax.annotation.Nullable
  private String quotedMsgId;

  public static final String JSON_PROPERTY_CHAT_ID = "chatId";
  @javax.annotation.Nullable
  private String chatId;

  public static final String JSON_PROPERTY_PHONE = "phone";
  @javax.annotation.Nullable
  private Integer phone;

  public SendFlowRequest1() { 
  }

  public SendFlowRequest1 body(@javax.annotation.Nonnull String body) {
    this.body = body;
    return this;
  }

  /**
   * Get body
   * @return body
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BODY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBody() {
    return body;
  }


  @JsonProperty(value = JSON_PROPERTY_BODY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBody(@javax.annotation.Nonnull String body) {
    this.body = body;
  }


  public SendFlowRequest1 header(@javax.annotation.Nullable SendFlowRequest1Header header) {
    this.header = header;
    return this;
  }

  /**
   * Get header
   * @return header
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEADER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SendFlowRequest1Header getHeader() {
    return header;
  }


  @JsonProperty(value = JSON_PROPERTY_HEADER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeader(@javax.annotation.Nullable SendFlowRequest1Header header) {
    this.header = header;
  }


  public SendFlowRequest1 footer(@javax.annotation.Nullable String footer) {
    this.footer = footer;
    return this;
  }

  /**
   * Get footer
   * @return footer
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FOOTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFooter() {
    return footer;
  }


  @JsonProperty(value = JSON_PROPERTY_FOOTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFooter(@javax.annotation.Nullable String footer) {
    this.footer = footer;
  }


  public SendFlowRequest1 flowId(@javax.annotation.Nonnull String flowId) {
    this.flowId = flowId;
    return this;
  }

  /**
   * Get flowId
   * @return flowId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FLOW_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFlowId() {
    return flowId;
  }


  @JsonProperty(value = JSON_PROPERTY_FLOW_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFlowId(@javax.annotation.Nonnull String flowId) {
    this.flowId = flowId;
  }


  public SendFlowRequest1 flowToken(@javax.annotation.Nonnull String flowToken) {
    this.flowToken = flowToken;
    return this;
  }

  /**
   * Get flowToken
   * @return flowToken
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FLOW_TOKEN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFlowToken() {
    return flowToken;
  }


  @JsonProperty(value = JSON_PROPERTY_FLOW_TOKEN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFlowToken(@javax.annotation.Nonnull String flowToken) {
    this.flowToken = flowToken;
  }


  public SendFlowRequest1 flowCta(@javax.annotation.Nonnull String flowCta) {
    this.flowCta = flowCta;
    return this;
  }

  /**
   * Get flowCta
   * @return flowCta
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FLOW_CTA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFlowCta() {
    return flowCta;
  }


  @JsonProperty(value = JSON_PROPERTY_FLOW_CTA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFlowCta(@javax.annotation.Nonnull String flowCta) {
    this.flowCta = flowCta;
  }


  public SendFlowRequest1 flowAction(@javax.annotation.Nullable FlowActionEnum flowAction) {
    this.flowAction = flowAction;
    return this;
  }

  /**
   * Get flowAction
   * @return flowAction
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FLOW_ACTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FlowActionEnum getFlowAction() {
    return flowAction;
  }


  @JsonProperty(value = JSON_PROPERTY_FLOW_ACTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowAction(@javax.annotation.Nullable FlowActionEnum flowAction) {
    this.flowAction = flowAction;
  }


  public SendFlowRequest1 flowActionPayload(@javax.annotation.Nullable Object flowActionPayload) {
    this.flowActionPayload = flowActionPayload;
    return this;
  }

  /**
   * Get flowActionPayload
   * @return flowActionPayload
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FLOW_ACTION_PAYLOAD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Object getFlowActionPayload() {
    return flowActionPayload;
  }


  @JsonProperty(value = JSON_PROPERTY_FLOW_ACTION_PAYLOAD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowActionPayload(@javax.annotation.Nullable Object flowActionPayload) {
    this.flowActionPayload = flowActionPayload;
  }


  public SendFlowRequest1 flowMessageVersion(@javax.annotation.Nullable String flowMessageVersion) {
    this.flowMessageVersion = flowMessageVersion;
    return this;
  }

  /**
   * Get flowMessageVersion
   * @return flowMessageVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FLOW_MESSAGE_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFlowMessageVersion() {
    return flowMessageVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_FLOW_MESSAGE_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowMessageVersion(@javax.annotation.Nullable String flowMessageVersion) {
    this.flowMessageVersion = flowMessageVersion;
  }


  public SendFlowRequest1 mode(@javax.annotation.Nullable ModeEnum mode) {
    this.mode = mode;
    return this;
  }

  /**
   * Get mode
   * @return mode
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ModeEnum getMode() {
    return mode;
  }


  @JsonProperty(value = JSON_PROPERTY_MODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMode(@javax.annotation.Nullable ModeEnum mode) {
    this.mode = mode;
  }


  public SendFlowRequest1 flowActionData(@javax.annotation.Nullable Object flowActionData) {
    this.flowActionData = flowActionData;
    return this;
  }

  /**
   * Get flowActionData
   * @return flowActionData
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FLOW_ACTION_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Object getFlowActionData() {
    return flowActionData;
  }


  @JsonProperty(value = JSON_PROPERTY_FLOW_ACTION_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowActionData(@javax.annotation.Nullable Object flowActionData) {
    this.flowActionData = flowActionData;
  }


  public SendFlowRequest1 flowActionScreen(@javax.annotation.Nullable String flowActionScreen) {
    this.flowActionScreen = flowActionScreen;
    return this;
  }

  /**
   * Get flowActionScreen
   * @return flowActionScreen
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FLOW_ACTION_SCREEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFlowActionScreen() {
    return flowActionScreen;
  }


  @JsonProperty(value = JSON_PROPERTY_FLOW_ACTION_SCREEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowActionScreen(@javax.annotation.Nullable String flowActionScreen) {
    this.flowActionScreen = flowActionScreen;
  }


  public SendFlowRequest1 quotedMsgId(@javax.annotation.Nullable String quotedMsgId) {
    this.quotedMsgId = quotedMsgId;
    return this;
  }

  /**
   * Get quotedMsgId
   * @return quotedMsgId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUOTED_MSG_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getQuotedMsgId() {
    return quotedMsgId;
  }


  @JsonProperty(value = JSON_PROPERTY_QUOTED_MSG_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuotedMsgId(@javax.annotation.Nullable String quotedMsgId) {
    this.quotedMsgId = quotedMsgId;
  }


  public SendFlowRequest1 chatId(@javax.annotation.Nullable String chatId) {
    this.chatId = chatId;
    return this;
  }

  /**
   * Get chatId
   * @return chatId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHAT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getChatId() {
    return chatId;
  }


  @JsonProperty(value = JSON_PROPERTY_CHAT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChatId(@javax.annotation.Nullable String chatId) {
    this.chatId = chatId;
  }


  public SendFlowRequest1 phone(@javax.annotation.Nullable Integer phone) {
    this.phone = phone;
    return this;
  }

  /**
   * Get phone
   * @return phone
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PHONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getPhone() {
    return phone;
  }


  @JsonProperty(value = JSON_PROPERTY_PHONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(@javax.annotation.Nullable Integer phone) {
    this.phone = phone;
  }


  /**
   * Return true if this sendFlow_request_1 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendFlowRequest1 sendFlowRequest1 = (SendFlowRequest1) o;
    return Objects.equals(this.body, sendFlowRequest1.body) &&
        Objects.equals(this.header, sendFlowRequest1.header) &&
        Objects.equals(this.footer, sendFlowRequest1.footer) &&
        Objects.equals(this.flowId, sendFlowRequest1.flowId) &&
        Objects.equals(this.flowToken, sendFlowRequest1.flowToken) &&
        Objects.equals(this.flowCta, sendFlowRequest1.flowCta) &&
        Objects.equals(this.flowAction, sendFlowRequest1.flowAction) &&
        Objects.equals(this.flowActionPayload, sendFlowRequest1.flowActionPayload) &&
        Objects.equals(this.flowMessageVersion, sendFlowRequest1.flowMessageVersion) &&
        Objects.equals(this.mode, sendFlowRequest1.mode) &&
        Objects.equals(this.flowActionData, sendFlowRequest1.flowActionData) &&
        Objects.equals(this.flowActionScreen, sendFlowRequest1.flowActionScreen) &&
        Objects.equals(this.quotedMsgId, sendFlowRequest1.quotedMsgId) &&
        Objects.equals(this.chatId, sendFlowRequest1.chatId) &&
        Objects.equals(this.phone, sendFlowRequest1.phone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(body, header, footer, flowId, flowToken, flowCta, flowAction, flowActionPayload, flowMessageVersion, mode, flowActionData, flowActionScreen, quotedMsgId, chatId, phone);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendFlowRequest1 {\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    footer: ").append(toIndentedString(footer)).append("\n");
    sb.append("    flowId: ").append(toIndentedString(flowId)).append("\n");
    sb.append("    flowToken: ").append(toIndentedString(flowToken)).append("\n");
    sb.append("    flowCta: ").append(toIndentedString(flowCta)).append("\n");
    sb.append("    flowAction: ").append(toIndentedString(flowAction)).append("\n");
    sb.append("    flowActionPayload: ").append(toIndentedString(flowActionPayload)).append("\n");
    sb.append("    flowMessageVersion: ").append(toIndentedString(flowMessageVersion)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    flowActionData: ").append(toIndentedString(flowActionData)).append("\n");
    sb.append("    flowActionScreen: ").append(toIndentedString(flowActionScreen)).append("\n");
    sb.append("    quotedMsgId: ").append(toIndentedString(quotedMsgId)).append("\n");
    sb.append("    chatId: ").append(toIndentedString(chatId)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `body` to the URL query string
    if (getBody() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbody%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBody()))));
    }

    // add `header` to the URL query string
    if (getHeader() != null) {
      joiner.add(getHeader().toUrlQueryString(prefix + "header" + suffix));
    }

    // add `footer` to the URL query string
    if (getFooter() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfooter%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFooter()))));
    }

    // add `flowId` to the URL query string
    if (getFlowId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sflowId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFlowId()))));
    }

    // add `flowToken` to the URL query string
    if (getFlowToken() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sflowToken%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFlowToken()))));
    }

    // add `flowCta` to the URL query string
    if (getFlowCta() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sflowCta%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFlowCta()))));
    }

    // add `flowAction` to the URL query string
    if (getFlowAction() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sflowAction%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFlowAction()))));
    }

    // add `flowActionPayload` to the URL query string
    if (getFlowActionPayload() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sflowActionPayload%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFlowActionPayload()))));
    }

    // add `flowMessageVersion` to the URL query string
    if (getFlowMessageVersion() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sflowMessageVersion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFlowMessageVersion()))));
    }

    // add `mode` to the URL query string
    if (getMode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMode()))));
    }

    // add `flowActionData` to the URL query string
    if (getFlowActionData() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sflowActionData%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFlowActionData()))));
    }

    // add `flowActionScreen` to the URL query string
    if (getFlowActionScreen() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sflowActionScreen%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFlowActionScreen()))));
    }

    // add `quotedMsgId` to the URL query string
    if (getQuotedMsgId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squotedMsgId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuotedMsgId()))));
    }

    // add `chatId` to the URL query string
    if (getChatId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schatId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChatId()))));
    }

    // add `phone` to the URL query string
    if (getPhone() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sphone%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPhone()))));
    }

    return joiner.toString();
  }
}

