/*
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.onemsg.sdk.model;

import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.onemsg.sdk.ApiClient;
/**
 * SendAddressMessageRequest
 */
@JsonPropertyOrder({
  SendAddressMessageRequest.JSON_PROPERTY_PHONE,
  SendAddressMessageRequest.JSON_PROPERTY_CHAT_ID,
  SendAddressMessageRequest.JSON_PROPERTY_BODY,
  SendAddressMessageRequest.JSON_PROPERTY_COUNTRY,
  SendAddressMessageRequest.JSON_PROPERTY_VALUES,
  SendAddressMessageRequest.JSON_PROPERTY_SAVED_ADDRESSES,
  SendAddressMessageRequest.JSON_PROPERTY_VALIDATION_ERRORS,
  SendAddressMessageRequest.JSON_PROPERTY_QUOTED_MSG_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-20T11:31:39.159231868+02:00[Europe/Berlin]", comments = "Generator version: 7.22.0")
public class SendAddressMessageRequest {
  public static final String JSON_PROPERTY_PHONE = "phone";
  @javax.annotation.Nullable
  private Integer phone;

  public static final String JSON_PROPERTY_CHAT_ID = "chatId";
  @javax.annotation.Nullable
  private String chatId;

  public static final String JSON_PROPERTY_BODY = "body";
  @javax.annotation.Nonnull
  private String body;

  /**
   * Address form country. Defaults to IN if omitted.
   */
  public enum CountryEnum {
    IN(String.valueOf("IN")),
    
    SG(String.valueOf("SG"));

    private String value;

    CountryEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CountryEnum fromValue(String value) {
      for (CountryEnum b : CountryEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @javax.annotation.Nullable
  private CountryEnum country;

  public static final String JSON_PROPERTY_VALUES = "values";
  @javax.annotation.Nullable
  private Map<String, Object> values = new HashMap<>();

  public static final String JSON_PROPERTY_SAVED_ADDRESSES = "saved_addresses";
  @javax.annotation.Nullable
  private List<Map<String, Object>> savedAddresses = new ArrayList<>();

  public static final String JSON_PROPERTY_VALIDATION_ERRORS = "validation_errors";
  @javax.annotation.Nullable
  private Map<String, Object> validationErrors = new HashMap<>();

  public static final String JSON_PROPERTY_QUOTED_MSG_ID = "quotedMsgId";
  @javax.annotation.Nullable
  private String quotedMsgId;

  public SendAddressMessageRequest() { 
  }

  public SendAddressMessageRequest phone(@javax.annotation.Nullable Integer phone) {
    this.phone = phone;
    return this;
  }

  /**
   * Recipient phone (E.164 digits, no +). Must match country.
   * @return phone
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PHONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getPhone() {
    return phone;
  }


  @JsonProperty(value = JSON_PROPERTY_PHONE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(@javax.annotation.Nullable Integer phone) {
    this.phone = phone;
  }


  public SendAddressMessageRequest chatId(@javax.annotation.Nullable String chatId) {
    this.chatId = chatId;
    return this;
  }

  /**
   * Get chatId
   * @return chatId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHAT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getChatId() {
    return chatId;
  }


  @JsonProperty(value = JSON_PROPERTY_CHAT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChatId(@javax.annotation.Nullable String chatId) {
    this.chatId = chatId;
  }


  public SendAddressMessageRequest body(@javax.annotation.Nonnull String body) {
    this.body = body;
    return this;
  }

  /**
   * Body text shown with the address request
   * @return body
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BODY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBody() {
    return body;
  }


  @JsonProperty(value = JSON_PROPERTY_BODY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBody(@javax.annotation.Nonnull String body) {
    this.body = body;
  }


  public SendAddressMessageRequest country(@javax.annotation.Nullable CountryEnum country) {
    this.country = country;
    return this;
  }

  /**
   * Address form country. Defaults to IN if omitted.
   * @return country
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CountryEnum getCountry() {
    return country;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@javax.annotation.Nullable CountryEnum country) {
    this.country = country;
  }


  public SendAddressMessageRequest values(@javax.annotation.Nullable Map<String, Object> values) {
    this.values = values;
    return this;
  }

  public SendAddressMessageRequest putValuesItem(String key, Object valuesItem) {
    if (this.values == null) {
      this.values = new HashMap<>();
    }
    this.values.put(key, valuesItem);
    return this;
  }

  /**
   * Optional prefilled address fields
   * @return values
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALUES, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getValues() {
    return values;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUES, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setValues(@javax.annotation.Nullable Map<String, Object> values) {
    this.values = values;
  }


  public SendAddressMessageRequest savedAddresses(@javax.annotation.Nullable List<Map<String, Object>> savedAddresses) {
    this.savedAddresses = savedAddresses;
    return this;
  }

  public SendAddressMessageRequest addSavedAddressesItem(Map<String, Object> savedAddressesItem) {
    if (this.savedAddresses == null) {
      this.savedAddresses = new ArrayList<>();
    }
    this.savedAddresses.add(savedAddressesItem);
    return this;
  }

  /**
   * Optional previously saved addresses for the user
   * @return savedAddresses
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SAVED_ADDRESSES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Map<String, Object>> getSavedAddresses() {
    return savedAddresses;
  }


  @JsonProperty(value = JSON_PROPERTY_SAVED_ADDRESSES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSavedAddresses(@javax.annotation.Nullable List<Map<String, Object>> savedAddresses) {
    this.savedAddresses = savedAddresses;
  }


  public SendAddressMessageRequest validationErrors(@javax.annotation.Nullable Map<String, Object> validationErrors) {
    this.validationErrors = validationErrors;
    return this;
  }

  public SendAddressMessageRequest putValidationErrorsItem(String key, Object validationErrorsItem) {
    if (this.validationErrors == null) {
      this.validationErrors = new HashMap<>();
    }
    this.validationErrors.put(key, validationErrorsItem);
    return this;
  }

  /**
   * Optional field validation errors when re-prompting
   * @return validationErrors
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALIDATION_ERRORS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getValidationErrors() {
    return validationErrors;
  }


  @JsonProperty(value = JSON_PROPERTY_VALIDATION_ERRORS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidationErrors(@javax.annotation.Nullable Map<String, Object> validationErrors) {
    this.validationErrors = validationErrors;
  }


  public SendAddressMessageRequest quotedMsgId(@javax.annotation.Nullable String quotedMsgId) {
    this.quotedMsgId = quotedMsgId;
    return this;
  }

  /**
   * Get quotedMsgId
   * @return quotedMsgId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUOTED_MSG_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getQuotedMsgId() {
    return quotedMsgId;
  }


  @JsonProperty(value = JSON_PROPERTY_QUOTED_MSG_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuotedMsgId(@javax.annotation.Nullable String quotedMsgId) {
    this.quotedMsgId = quotedMsgId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   * @param key the name of the property
   * @param value the value of the property
   * @return self reference
   */
  @JsonAnySetter
  public SendAddressMessageRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) properties.
   * @return the additional (undeclared) properties
   */
  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   * @param key the name of the property
   * @return the additional (undeclared) property with the specified name
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }

  /**
   * Return true if this sendAddressMessage_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendAddressMessageRequest sendAddressMessageRequest = (SendAddressMessageRequest) o;
    return Objects.equals(this.phone, sendAddressMessageRequest.phone) &&
        Objects.equals(this.chatId, sendAddressMessageRequest.chatId) &&
        Objects.equals(this.body, sendAddressMessageRequest.body) &&
        Objects.equals(this.country, sendAddressMessageRequest.country) &&
        Objects.equals(this.values, sendAddressMessageRequest.values) &&
        Objects.equals(this.savedAddresses, sendAddressMessageRequest.savedAddresses) &&
        Objects.equals(this.validationErrors, sendAddressMessageRequest.validationErrors) &&
        Objects.equals(this.quotedMsgId, sendAddressMessageRequest.quotedMsgId)&&
        Objects.equals(this.additionalProperties, sendAddressMessageRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phone, chatId, body, country, values, savedAddresses, validationErrors, quotedMsgId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendAddressMessageRequest {\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    chatId: ").append(toIndentedString(chatId)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    savedAddresses: ").append(toIndentedString(savedAddresses)).append("\n");
    sb.append("    validationErrors: ").append(toIndentedString(validationErrors)).append("\n");
    sb.append("    quotedMsgId: ").append(toIndentedString(quotedMsgId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `phone` to the URL query string
    if (getPhone() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sphone%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPhone()))));
    }

    // add `chatId` to the URL query string
    if (getChatId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schatId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChatId()))));
    }

    // add `body` to the URL query string
    if (getBody() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbody%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBody()))));
    }

    // add `country` to the URL query string
    if (getCountry() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scountry%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCountry()))));
    }

    // add `values` to the URL query string
    if (getValues() != null) {
      for (String _key : getValues().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%svalues%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getValues().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getValues().get(_key)))));
      }
    }

    // add `saved_addresses` to the URL query string
    if (getSavedAddresses() != null) {
      for (int i = 0; i < getSavedAddresses().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%ssaved_addresses%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getSavedAddresses().get(i)))));
      }
    }

    // add `validation_errors` to the URL query string
    if (getValidationErrors() != null) {
      for (String _key : getValidationErrors().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%svalidation_errors%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getValidationErrors().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getValidationErrors().get(_key)))));
      }
    }

    // add `quotedMsgId` to the URL query string
    if (getQuotedMsgId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squotedMsgId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuotedMsgId()))));
    }

    return joiner.toString();
  }
}

