/*
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.onemsg.sdk.model;

import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.onemsg.sdk.ApiClient;
/**
 * UpdateMeRequest
 */
@JsonPropertyOrder({
  UpdateMeRequest.JSON_PROPERTY_ABOUT,
  UpdateMeRequest.JSON_PROPERTY_ADDRESS,
  UpdateMeRequest.JSON_PROPERTY_DESCRIPTION,
  UpdateMeRequest.JSON_PROPERTY_EMAIL,
  UpdateMeRequest.JSON_PROPERTY_VERTICAL,
  UpdateMeRequest.JSON_PROPERTY_PHOTO,
  UpdateMeRequest.JSON_PROPERTY_WEBSITES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-24T12:33:30.009264922Z[Etc/UTC]", comments = "Generator version: 7.22.0")
public class UpdateMeRequest {
  public static final String JSON_PROPERTY_ABOUT = "about";
  @javax.annotation.Nullable
  private String about;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  @javax.annotation.Nullable
  private String address;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @javax.annotation.Nullable
  private String email;

  public static final String JSON_PROPERTY_VERTICAL = "vertical";
  @javax.annotation.Nullable
  private String vertical;

  public static final String JSON_PROPERTY_PHOTO = "photo";
  @javax.annotation.Nullable
  private String photo;

  public static final String JSON_PROPERTY_WEBSITES = "websites";
  @javax.annotation.Nullable
  private List<String> websites = new ArrayList<>();

  public UpdateMeRequest() { 
  }

  public UpdateMeRequest about(@javax.annotation.Nullable String about) {
    this.about = about;
    return this;
  }

  /**
   * Profile About section
   * @return about
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ABOUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAbout() {
    return about;
  }


  @JsonProperty(value = JSON_PROPERTY_ABOUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAbout(@javax.annotation.Nullable String about) {
    this.about = about;
  }


  public UpdateMeRequest address(@javax.annotation.Nullable String address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAddress() {
    return address;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(@javax.annotation.Nullable String address) {
    this.address = address;
  }


  public UpdateMeRequest description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Business description (max 256 characters)
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public UpdateMeRequest email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEmail() {
    return email;
  }


  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public UpdateMeRequest vertical(@javax.annotation.Nullable String vertical) {
    this.vertical = vertical;
    return this;
  }

  /**
   * Industry of the business
   * @return vertical
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERTICAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getVertical() {
    return vertical;
  }


  @JsonProperty(value = JSON_PROPERTY_VERTICAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVertical(@javax.annotation.Nullable String vertical) {
    this.vertical = vertical;
  }


  public UpdateMeRequest photo(@javax.annotation.Nullable String photo) {
    this.photo = photo;
    return this;
  }

  /**
   * HTTPS URL or data:image/...;base64,... payload
   * @return photo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PHOTO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPhoto() {
    return photo;
  }


  @JsonProperty(value = JSON_PROPERTY_PHOTO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhoto(@javax.annotation.Nullable String photo) {
    this.photo = photo;
  }


  public UpdateMeRequest websites(@javax.annotation.Nullable List<String> websites) {
    this.websites = websites;
    return this;
  }

  public UpdateMeRequest addWebsitesItem(String websitesItem) {
    if (this.websites == null) {
      this.websites = new ArrayList<>();
    }
    this.websites.add(websitesItem);
    return this;
  }

  /**
   * Get websites
   * @return websites
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEBSITES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getWebsites() {
    return websites;
  }


  @JsonProperty(value = JSON_PROPERTY_WEBSITES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebsites(@javax.annotation.Nullable List<String> websites) {
    this.websites = websites;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   * @param key the name of the property
   * @param value the value of the property
   * @return self reference
   */
  @JsonAnySetter
  public UpdateMeRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) properties.
   * @return the additional (undeclared) properties
   */
  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   * @param key the name of the property
   * @return the additional (undeclared) property with the specified name
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }

  /**
   * Return true if this updateMe_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateMeRequest updateMeRequest = (UpdateMeRequest) o;
    return Objects.equals(this.about, updateMeRequest.about) &&
        Objects.equals(this.address, updateMeRequest.address) &&
        Objects.equals(this.description, updateMeRequest.description) &&
        Objects.equals(this.email, updateMeRequest.email) &&
        Objects.equals(this.vertical, updateMeRequest.vertical) &&
        Objects.equals(this.photo, updateMeRequest.photo) &&
        Objects.equals(this.websites, updateMeRequest.websites)&&
        Objects.equals(this.additionalProperties, updateMeRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(about, address, description, email, vertical, photo, websites, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateMeRequest {\n");
    sb.append("    about: ").append(toIndentedString(about)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    vertical: ").append(toIndentedString(vertical)).append("\n");
    sb.append("    photo: ").append(toIndentedString(photo)).append("\n");
    sb.append("    websites: ").append(toIndentedString(websites)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `about` to the URL query string
    if (getAbout() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sabout%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAbout()))));
    }

    // add `address` to the URL query string
    if (getAddress() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saddress%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAddress()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `email` to the URL query string
    if (getEmail() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%semail%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEmail()))));
    }

    // add `vertical` to the URL query string
    if (getVertical() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svertical%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVertical()))));
    }

    // add `photo` to the URL query string
    if (getPhoto() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sphoto%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPhoto()))));
    }

    // add `websites` to the URL query string
    if (getWebsites() != null) {
      for (int i = 0; i < getWebsites().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%swebsites%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getWebsites().get(i)))));
      }
    }

    return joiner.toString();
  }
}

