=begin
#1MSG WhatsApp Business API (Public)

#Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 

The version of the OpenAPI document: 1.0.0
Contact: support@1msg.io
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneMsgSdk::SendTemplateRequestLanguage
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OneMsgSdk::SendTemplateRequestLanguage do
  #let(:instance) { OneMsgSdk::SendTemplateRequestLanguage.new }

  describe 'test an instance of SendTemplateRequestLanguage' do
    it 'should create an instance of SendTemplateRequestLanguage' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OneMsgSdk::SendTemplateRequestLanguage)
    end
  end

  describe 'test attribute "policy"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
