# coding: utf-8

"""
    1MSG WhatsApp Business API (Public)

    Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 

    The version of the OpenAPI document: 1.0.0
    Contact: support@1msg.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from one_msg_sdk.models.send_contact_request_contacts_inner import SendContactRequestContactsInner

class TestSendContactRequestContactsInner(unittest.TestCase):
    """SendContactRequestContactsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendContactRequestContactsInner:
        """Test SendContactRequestContactsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendContactRequestContactsInner`
        """
        model = SendContactRequestContactsInner()
        if include_optional:
            return SendContactRequestContactsInner(
                name = one_msg_sdk.models.send_contact_request_contacts_inner_name.sendContact_request_contacts_inner_name(
                    formatted_name = '', 
                    first_name = '', 
                    last_name = '', 
                    middle_name = '', 
                    suffix = '', 
                    prefix = '', ),
                birthday = '',
                addresses = [
                    null
                    ],
                emails = [
                    null
                    ],
                org = one_msg_sdk.models.send_contact_request_contacts_inner_org.sendContact_request_contacts_inner_org(
                    company = '', 
                    department = '', 
                    title = '', ),
                phones = [
                    one_msg_sdk.models.send_contact_request_contacts_inner_phones_inner.sendContact_request_contacts_inner_phones_inner(
                        phone = '', 
                        type = '', 
                        wa_id = '', )
                    ],
                urls = [
                    null
                    ]
            )
        else:
            return SendContactRequestContactsInner(
        )
        """

    def testSendContactRequestContactsInner(self):
        """Test SendContactRequestContactsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
