# coding: utf-8

"""
    1MSG WhatsApp Business API (Public)

    Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 

    The version of the OpenAPI document: 1.0.0
    Contact: support@1msg.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from one_msg_sdk.models.send_list_request_sections_inner import SendListRequestSectionsInner

class TestSendListRequestSectionsInner(unittest.TestCase):
    """SendListRequestSectionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendListRequestSectionsInner:
        """Test SendListRequestSectionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendListRequestSectionsInner`
        """
        model = SendListRequestSectionsInner()
        if include_optional:
            return SendListRequestSectionsInner(
                title = '',
                rows = [
                    one_msg_sdk.models.send_list_request_sections_inner_rows_inner.sendList_request_sections_inner_rows_inner(
                        id = '', 
                        title = '', 
                        description = '', )
                    ]
            )
        else:
            return SendListRequestSectionsInner(
        )
        """

    def testSendListRequestSectionsInner(self):
        """Test SendListRequestSectionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
