# coding: utf-8

"""
    1MSG WhatsApp Business API (Public)

    Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 

    The version of the OpenAPI document: 1.0.0
    Contact: support@1msg.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from one_msg_sdk.api.catalog_api import CatalogApi


class TestCatalogApi(unittest.TestCase):
    """CatalogApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CatalogApi()

    def tearDown(self) -> None:
        pass

    def test_create_commerce(self) -> None:
        """Test case for create_commerce

        Set Commerce Settings
        """
        pass

    def test_get_commerce(self) -> None:
        """Test case for get_commerce

        Get Commerce Settings
        """
        pass


if __name__ == '__main__':
    unittest.main()
