# coding: utf-8

"""
    1MSG WhatsApp Business API (Public)

    Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 

    The version of the OpenAPI document: 1.0.0
    Contact: support@1msg.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from one_msg_sdk.models.send_order_details_request_order_items_inner import SendOrderDetailsRequestOrderItemsInner

class TestSendOrderDetailsRequestOrderItemsInner(unittest.TestCase):
    """SendOrderDetailsRequestOrderItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendOrderDetailsRequestOrderItemsInner:
        """Test SendOrderDetailsRequestOrderItemsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendOrderDetailsRequestOrderItemsInner`
        """
        model = SendOrderDetailsRequestOrderItemsInner()
        if include_optional:
            return SendOrderDetailsRequestOrderItemsInner(
                retailer_id = 'SKU-1',
                name = 'Item',
                quantity = 1,
                amount = { }
            )
        else:
            return SendOrderDetailsRequestOrderItemsInner(
        )
        """

    def testSendOrderDetailsRequestOrderItemsInner(self):
        """Test SendOrderDetailsRequestOrderItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
