# coding: utf-8

"""
    1MSG WhatsApp Business API (Public)

    Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 

    The version of the OpenAPI document: 1.0.0
    Contact: support@1msg.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from one_msg_sdk.models.send_flow_request1 import SendFlowRequest1

class TestSendFlowRequest1(unittest.TestCase):
    """SendFlowRequest1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendFlowRequest1:
        """Test SendFlowRequest1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendFlowRequest1`
        """
        model = SendFlowRequest1()
        if include_optional:
            return SendFlowRequest1(
                body = '',
                header = None,
                footer = '',
                flow_id = '',
                flow_token = '',
                flow_cta = '',
                flow_action = 'navigate',
                flow_action_payload = None,
                flow_message_version = '',
                mode = 'draft',
                flow_action_data = None,
                flow_action_screen = '',
                quoted_msg_id = '',
                chat_id = '',
                phone = 56
            )
        else:
            return SendFlowRequest1(
                body = '',
                flow_id = '',
                flow_token = '',
                flow_cta = '',
        )
        """

    def testSendFlowRequest1(self):
        """Test SendFlowRequest1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
