# -*- encoding: utf-8 -*-

=begin
#1MSG WhatsApp Business API (Public)

#Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 

The version of the OpenAPI document: 1.0.0
Contact: support@1msg.io
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "one_msg_sdk/version"

Gem::Specification.new do |s|
  s.name        = "one_msg_sdk"
  s.version     = OneMsgSdk::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["1MSG"]
  s.email       = ["support@1msg.io"]
  s.homepage    = "https://github.com/1msg/1msg-sdk"
  s.summary     = "Official Ruby SDK for the 1MSG WhatsApp Business API"
  s.description = "Official Ruby client for the 1MSG WhatsApp Business API"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'faraday', '>= 1.0.1', '< 3.0'
  s.add_runtime_dependency 'faraday-multipart'
  s.add_runtime_dependency 'marcel'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
