/*
 * 1MSG WhatsApp Business API (Public)
 *
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using OneMsg.ChatApi.Client;
using OneMsg.ChatApi.Api;
// uncomment below to import models
//using OneMsg.ChatApi.Model;

namespace OneMsg.ChatApi.Test.Api
{
    /// <summary>
    ///  Class for testing MessagingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MessagingApiTests : IDisposable
    {
        private MessagingApi instance;

        public MessagingApiTests()
        {
            instance = new MessagingApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessagingApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MessagingApi
            //Assert.IsType<MessagingApi>(instance);
        }

        /// <summary>
        /// Test CreateReadMessage
        /// </summary>
        [Fact]
        public void CreateReadMessageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //string messageId = null;
            //string msgId = null;
            //bool? typingIndicator = null;
            //var response = instance.CreateReadMessage(token, messageId, msgId, typingIndicator);
            //Assert.IsType<CreateReadMessage200Response>(response);
        }

        /// <summary>
        /// Test CreateUploadMedia
        /// </summary>
        [Fact]
        public void CreateUploadMediaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //Dictionary<string, Object> requestBody = null;
            //instance.CreateUploadMedia(token, requestBody);
        }

        /// <summary>
        /// Test DeleteMedia
        /// </summary>
        [Fact]
        public void DeleteMediaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //string mediaId = null;
            //var response = instance.DeleteMedia(token, mediaId);
            //Assert.IsType<SuccessResponse>(response);
        }

        /// <summary>
        /// Test DeleteMediaLegacy
        /// </summary>
        [Fact]
        public void DeleteMediaLegacyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //DeleteMediaLegacyRequest deleteMediaLegacyRequest = null;
            //var response = instance.DeleteMediaLegacy(token, deleteMediaLegacyRequest);
            //Assert.IsType<SuccessResponse>(response);
        }

        /// <summary>
        /// Test GetMmLiteStatus
        /// </summary>
        [Fact]
        public void GetMmLiteStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //var response = instance.GetMmLiteStatus(token);
            //Assert.IsType<GetMmLiteStatus200Response>(response);
        }

        /// <summary>
        /// Test ListMessages
        /// </summary>
        [Fact]
        public void ListMessagesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //var response = instance.ListMessages(token);
            //Assert.IsType<ListMessages200Response>(response);
        }

        /// <summary>
        /// Test RetrieveMedia
        /// </summary>
        [Fact]
        public void RetrieveMediaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //string mediaId = null;
            //var response = instance.RetrieveMedia(token, mediaId);
            //Assert.IsType<RetrieveMedia200Response>(response);
        }

        /// <summary>
        /// Test SendAddressMessage
        /// </summary>
        [Fact]
        public void SendAddressMessageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //SendAddressMessageRequest sendAddressMessageRequest = null;
            //var response = instance.SendAddressMessage(token, sendAddressMessageRequest);
            //Assert.IsType<MessageSentResponse>(response);
        }

        /// <summary>
        /// Test SendButton
        /// </summary>
        [Fact]
        public void SendButtonTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //SendButtonRequest sendButtonRequest = null;
            //var response = instance.SendButton(token, sendButtonRequest);
            //Assert.IsType<MessageSentResponse>(response);
        }

        /// <summary>
        /// Test SendCarousel
        /// </summary>
        [Fact]
        public void SendCarouselTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //List<Object> varParams = null;
            //string body = null;
            //string quotedMsgId = null;
            //string chatId = null;
            //int? phone = null;
            //var response = instance.SendCarousel(token, varParams, body, quotedMsgId, chatId, phone);
            //Assert.IsType<MessageSentResponse>(response);
        }

        /// <summary>
        /// Test SendContact
        /// </summary>
        [Fact]
        public void SendContactTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //SendContactRequest sendContactRequest = null;
            //var response = instance.SendContact(token, sendContactRequest);
            //Assert.IsType<MessageSentResponse>(response);
        }

        /// <summary>
        /// Test SendCtaUrl
        /// </summary>
        [Fact]
        public void SendCtaUrlTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //SendCtaUrlRequest sendCtaUrlRequest = null;
            //var response = instance.SendCtaUrl(token, sendCtaUrlRequest);
            //Assert.IsType<MessageSentResponse>(response);
        }

        /// <summary>
        /// Test SendFile
        /// </summary>
        [Fact]
        public void SendFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //string body = null;
            //string filename = null;
            //string mediaId = null;
            //string mediaType = null;
            //bool? voice = null;
            //string caption = null;
            //string quotedMsgId = null;
            //string chatId = null;
            //int? phone = null;
            //var response = instance.SendFile(token, body, filename, mediaId, mediaType, voice, caption, quotedMsgId, chatId, phone);
            //Assert.IsType<MessageSentResponse>(response);
        }

        /// <summary>
        /// Test SendFlow
        /// </summary>
        [Fact]
        public void SendFlowTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //string body = null;
            //string flowId = null;
            //string flowToken = null;
            //string flowCta = null;
            //SendFlowRequestHeader header = null;
            //string footer = null;
            //string flowAction = null;
            //Object flowActionPayload = null;
            //string flowMessageVersion = null;
            //string mode = null;
            //Object flowActionData = null;
            //string flowActionScreen = null;
            //string quotedMsgId = null;
            //string chatId = null;
            //int? phone = null;
            //var response = instance.SendFlow(token, body, flowId, flowToken, flowCta, header, footer, flowAction, flowActionPayload, flowMessageVersion, mode, flowActionData, flowActionScreen, quotedMsgId, chatId, phone);
            //Assert.IsType<MessageSentResponse>(response);
        }

        /// <summary>
        /// Test SendList
        /// </summary>
        [Fact]
        public void SendListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //SendListRequest sendListRequest = null;
            //var response = instance.SendList(token, sendListRequest);
            //Assert.IsType<MessageSentResponse>(response);
        }

        /// <summary>
        /// Test SendLocation
        /// </summary>
        [Fact]
        public void SendLocationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //string lat = null;
            //string lng = null;
            //string address = null;
            //string name = null;
            //string quotedMsgId = null;
            //string chatId = null;
            //int? phone = null;
            //var response = instance.SendLocation(token, lat, lng, address, name, quotedMsgId, chatId, phone);
            //Assert.IsType<MessageSentResponse>(response);
        }

        /// <summary>
        /// Test SendLocationRequest
        /// </summary>
        [Fact]
        public void SendLocationRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //SendLocationRequestRequest sendLocationRequestRequest = null;
            //var response = instance.SendLocationRequest(token, sendLocationRequestRequest);
            //Assert.IsType<MessageSentResponse>(response);
        }

        /// <summary>
        /// Test SendMessage
        /// </summary>
        [Fact]
        public void SendMessageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //string body = null;
            //string quotedMsgId = null;
            //string chatId = null;
            //int? phone = null;
            //var response = instance.SendMessage(token, body, quotedMsgId, chatId, phone);
            //Assert.IsType<MessageSentResponse>(response);
        }

        /// <summary>
        /// Test SendOrderDetails
        /// </summary>
        [Fact]
        public void SendOrderDetailsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //SendOrderDetailsRequest sendOrderDetailsRequest = null;
            //var response = instance.SendOrderDetails(token, sendOrderDetailsRequest);
            //Assert.IsType<MessageSentResponse>(response);
        }

        /// <summary>
        /// Test SendPaymentRequest
        /// </summary>
        [Fact]
        public void SendPaymentRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //SendPaymentRequestRequest sendPaymentRequestRequest = null;
            //var response = instance.SendPaymentRequest(token, sendPaymentRequestRequest);
            //Assert.IsType<MessageSentResponse>(response);
        }

        /// <summary>
        /// Test SendProduct
        /// </summary>
        [Fact]
        public void SendProductTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //Dictionary<string, Object> requestBody = null;
            //var response = instance.SendProduct(token, requestBody);
            //Assert.IsType<MessageSentResponse>(response);
        }

        /// <summary>
        /// Test SendReaction
        /// </summary>
        [Fact]
        public void SendReactionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //SendReactionRequest sendReactionRequest = null;
            //var response = instance.SendReaction(token, sendReactionRequest);
            //Assert.IsType<MessageSentResponse>(response);
        }

        /// <summary>
        /// Test SendSticker
        /// </summary>
        [Fact]
        public void SendStickerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //SendStickerRequest sendStickerRequest = null;
            //var response = instance.SendSticker(token, sendStickerRequest);
            //Assert.IsType<MessageSentResponse>(response);
        }
    }
}
