/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.onemsg.sdk.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.onemsg.sdk.model.CallingSettingsCallingSip
import io.onemsg.sdk.model.CallingSettingsCallingSipServersInner

class CallingSettingsCallingSipTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CallingSettingsCallingSip
        //val modelInstance = CallingSettingsCallingSip()

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `servers`
        should("test servers") {
            // uncomment below to test the property
            //modelInstance.servers shouldBe ("TODO")
        }

    }
}
