/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.onemsg.chat.model

import io.circe.{Decoder, DecodingFailure, Encoder, Json}
import io.circe.syntax._
import io.onemsg.chat.core.JsonSupport._

case class CreateReadMessageRequest(
  messageId: Option[String] = None,
  msgId: Option[String] = None,
  /* Show WhatsApp typing indicator (max 25s or until reply) */
  typingIndicator: Option[Boolean] = None
)
object CreateReadMessageRequest {
  implicit val encoderCreateReadMessageRequest: Encoder[CreateReadMessageRequest] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.messageId.map(v => "messageId" -> v.asJson),
        t.msgId.map(v => "msgId" -> v.asJson),
        t.typingIndicator.map(v => "typingIndicator" -> v.asJson)
      ).flatten
    }
  }
  implicit val decoderCreateReadMessageRequest: Decoder[CreateReadMessageRequest] = Decoder.instance { c =>
    for {
      messageId <- c.downField("messageId").as[Option[String]]
      msgId <- c.downField("msgId").as[Option[String]]
      typingIndicator <- c.downField("typingIndicator").as[Option[Boolean]]
    } yield CreateReadMessageRequest(
      messageId = messageId,
      msgId = msgId,
      typingIndicator = typingIndicator
    )
  }
}

