/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.onemsg.chat.model

import io.circe.{Decoder, DecodingFailure, Encoder, Json}
import io.circe.syntax._
import io.onemsg.chat.core.JsonSupport._

  /**
   * Standard error response
   */
case class ErrorResponse(
  /* Error message */
  error: Option[String] = None
)
object ErrorResponse {
  implicit val encoderErrorResponse: Encoder[ErrorResponse] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.error.map(v => "error" -> v.asJson)
      ).flatten
    }
  }
  implicit val decoderErrorResponse: Decoder[ErrorResponse] = Decoder.instance { c =>
    for {
      error <- c.downField("error").as[Option[String]]
    } yield ErrorResponse(
      error = error
    )
  }
}

