/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.onemsg.chat.model

import io.circe.{Decoder, DecodingFailure, Encoder, Json}
import io.circe.syntax._
import io.onemsg.chat.core.JsonSupport._

case class GetWhatsappBusinessEncryption200Response(
  /* Stored 2048-bit RSA public key (PEM) */
  businessPublicKey: Option[String] = None,
  businessPublicKeySignatureStatus: Option[GetWhatsappBusinessEncryption200ResponseEnums.BusinessPublicKeySignatureStatus] = None,
  data: Option[Seq[Map[String, io.circe.Json]]] = None
)
object GetWhatsappBusinessEncryption200Response {
  implicit val encoderGetWhatsappBusinessEncryption200Response: Encoder[GetWhatsappBusinessEncryption200Response] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.businessPublicKey.map(v => "business_public_key" -> v.asJson),
        t.businessPublicKeySignatureStatus.map(v => "business_public_key_signature_status" -> v.asJson),
        t.data.map(v => "data" -> v.asJson)
      ).flatten
    }
  }
  implicit val decoderGetWhatsappBusinessEncryption200Response: Decoder[GetWhatsappBusinessEncryption200Response] = Decoder.instance { c =>
    for {
      businessPublicKey <- c.downField("business_public_key").as[Option[String]]
      businessPublicKeySignatureStatus <- c.downField("business_public_key_signature_status").as[Option[GetWhatsappBusinessEncryption200ResponseEnums.BusinessPublicKeySignatureStatus]]
      data <- c.downField("data").as[Option[Seq[Map[String, io.circe.Json]]]]
    } yield GetWhatsappBusinessEncryption200Response(
      businessPublicKey = businessPublicKey,
      businessPublicKeySignatureStatus = businessPublicKeySignatureStatus,
      data = data
    )
  }
}

object GetWhatsappBusinessEncryption200ResponseEnums {

  type BusinessPublicKeySignatureStatus = BusinessPublicKeySignatureStatus.Value
  object BusinessPublicKeySignatureStatus extends Enumeration {
    val VALID = Value("VALID")
    val MISMATCH = Value("MISMATCH")
  }

}
