/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.onemsg.chat.model

import io.circe.{Decoder, DecodingFailure, Encoder, Json}
import io.circe.syntax._
import io.onemsg.chat.core.JsonSupport._

  /**
   * Response for successfully sent message
   */
case class MessageSentResponse(
  /* Whether the message was successfully queued for sending */
  sent: Option[Boolean] = None,
  /* Message ID */
  id: Option[String] = None,
  /* Status message */
  message: Option[String] = None,
  /* Detailed description */
  description: Option[String] = None
)
object MessageSentResponse {
  implicit val encoderMessageSentResponse: Encoder[MessageSentResponse] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.sent.map(v => "sent" -> v.asJson),
        t.id.map(v => "id" -> v.asJson),
        t.message.map(v => "message" -> v.asJson),
        t.description.map(v => "description" -> v.asJson)
      ).flatten
    }
  }
  implicit val decoderMessageSentResponse: Decoder[MessageSentResponse] = Decoder.instance { c =>
    for {
      sent <- c.downField("sent").as[Option[Boolean]]
      id <- c.downField("id").as[Option[String]]
      message <- c.downField("message").as[Option[String]]
      description <- c.downField("description").as[Option[String]]
    } yield MessageSentResponse(
      sent = sent,
      id = id,
      message = message,
      description = description
    )
  }
}

