/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.onemsg.chat.model

import io.circe.{Decoder, DecodingFailure, Encoder, Json}
import io.circe.syntax._
import io.onemsg.chat.core.JsonSupport._

case class PatchFlowsFlowIdAssets200Response(
  success: Option[Boolean] = None,
  validationErrors: Option[Seq[Map[String, io.circe.Json]]] = None,
  /* Error details returned by the provider. May be a string or a JSON object. */
  error: Option[io.circe.Json] = None
)
object PatchFlowsFlowIdAssets200Response {
  implicit val encoderPatchFlowsFlowIdAssets200Response: Encoder[PatchFlowsFlowIdAssets200Response] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.success.map(v => "success" -> v.asJson),
        t.validationErrors.map(v => "validationErrors" -> v.asJson),
        t.error.map(v => "error" -> v.asJson)
      ).flatten
    }
  }
  implicit val decoderPatchFlowsFlowIdAssets200Response: Decoder[PatchFlowsFlowIdAssets200Response] = Decoder.instance { c =>
    for {
      success <- c.downField("success").as[Option[Boolean]]
      validationErrors <- c.downField("validationErrors").as[Option[Seq[Map[String, io.circe.Json]]]]
      error <- c.downField("error").as[Option[io.circe.Json]]
    } yield PatchFlowsFlowIdAssets200Response(
      success = success,
      validationErrors = validationErrors,
      error = error
    )
  }
}

