/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.onemsg.chat.model

import io.circe.{Decoder, DecodingFailure, Encoder, Json}
import io.circe.syntax._
import io.onemsg.chat.core.JsonSupport._

case class SendTemplateRequestLanguage(
  policy: Option[String] = None,
  code: Option[String] = None
)
object SendTemplateRequestLanguage {
  implicit val encoderSendTemplateRequestLanguage: Encoder[SendTemplateRequestLanguage] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.policy.map(v => "policy" -> v.asJson),
        t.code.map(v => "code" -> v.asJson)
      ).flatten
    }
  }
  implicit val decoderSendTemplateRequestLanguage: Decoder[SendTemplateRequestLanguage] = Decoder.instance { c =>
    for {
      policy <- c.downField("policy").as[Option[String]]
      code <- c.downField("code").as[Option[String]]
    } yield SendTemplateRequestLanguage(
      policy = policy,
      code = code
    )
  }
}

