/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.onemsg.chat.model

import io.circe.{Decoder, DecodingFailure, Encoder, Json}
import io.circe.syntax._
import io.onemsg.chat.core.JsonSupport._

case class SendFlowRequest1(
  body: String,
  header: Option[SendFlowRequest1Header] = None,
  footer: Option[String] = None,
  flowId: String,
  flowToken: String,
  flowCta: String,
  flowAction: Option[SendFlowRequest1Enums.FlowAction] = None,
  flowActionPayload: Option[io.circe.Json] = None,
  flowMessageVersion: Option[String] = None,
  mode: Option[SendFlowRequest1Enums.Mode] = None,
  flowActionData: Option[io.circe.Json] = None,
  flowActionScreen: Option[String] = None,
  quotedMsgId: Option[String] = None,
  chatId: Option[String] = None,
  phone: Option[Int] = None
)
object SendFlowRequest1 {
  implicit val encoderSendFlowRequest1: Encoder[SendFlowRequest1] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        Some("body" -> t.body.asJson),
        t.header.map(v => "header" -> v.asJson),
        t.footer.map(v => "footer" -> v.asJson),
        Some("flowId" -> t.flowId.asJson),
        Some("flowToken" -> t.flowToken.asJson),
        Some("flowCta" -> t.flowCta.asJson),
        t.flowAction.map(v => "flowAction" -> v.asJson),
        t.flowActionPayload.map(v => "flowActionPayload" -> v.asJson),
        t.flowMessageVersion.map(v => "flowMessageVersion" -> v.asJson),
        t.mode.map(v => "mode" -> v.asJson),
        t.flowActionData.map(v => "flowActionData" -> v.asJson),
        t.flowActionScreen.map(v => "flowActionScreen" -> v.asJson),
        t.quotedMsgId.map(v => "quotedMsgId" -> v.asJson),
        t.chatId.map(v => "chatId" -> v.asJson),
        t.phone.map(v => "phone" -> v.asJson)
      ).flatten
    }
  }
  implicit val decoderSendFlowRequest1: Decoder[SendFlowRequest1] = Decoder.instance { c =>
    for {
      body <- c.downField("body").as[String]
      header <- c.downField("header").as[Option[SendFlowRequest1Header]]
      footer <- c.downField("footer").as[Option[String]]
      flowId <- c.downField("flowId").as[String]
      flowToken <- c.downField("flowToken").as[String]
      flowCta <- c.downField("flowCta").as[String]
      flowAction <- c.downField("flowAction").as[Option[SendFlowRequest1Enums.FlowAction]]
      flowActionPayload <- c.downField("flowActionPayload").as[Option[io.circe.Json]]
      flowMessageVersion <- c.downField("flowMessageVersion").as[Option[String]]
      mode <- c.downField("mode").as[Option[SendFlowRequest1Enums.Mode]]
      flowActionData <- c.downField("flowActionData").as[Option[io.circe.Json]]
      flowActionScreen <- c.downField("flowActionScreen").as[Option[String]]
      quotedMsgId <- c.downField("quotedMsgId").as[Option[String]]
      chatId <- c.downField("chatId").as[Option[String]]
      phone <- c.downField("phone").as[Option[Int]]
    } yield SendFlowRequest1(
      body = body,
      header = header,
      footer = footer,
      flowId = flowId,
      flowToken = flowToken,
      flowCta = flowCta,
      flowAction = flowAction,
      flowActionPayload = flowActionPayload,
      flowMessageVersion = flowMessageVersion,
      mode = mode,
      flowActionData = flowActionData,
      flowActionScreen = flowActionScreen,
      quotedMsgId = quotedMsgId,
      chatId = chatId,
      phone = phone
    )
  }
}

object SendFlowRequest1Enums {

  type FlowAction = FlowAction.Value
  type Mode = Mode.Value
  object FlowAction extends Enumeration {
    val Navigate = Value("navigate")
    val DataExchange = Value("data_exchange")
  }

  object Mode extends Enumeration {
    val Draft = Value("draft")
    val Published = Value("published")
  }

}
