/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.onemsg.chat.model

import io.circe.{Decoder, DecodingFailure, Encoder, Json}
import io.circe.syntax._
import io.onemsg.chat.core.JsonSupport._

case class SendButtonRequestSectionsInnerReply(
  id: Option[String] = None,
  title: Option[String] = None
)
object SendButtonRequestSectionsInnerReply {
  implicit val encoderSendButtonRequestSectionsInnerReply: Encoder[SendButtonRequestSectionsInnerReply] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.id.map(v => "id" -> v.asJson),
        t.title.map(v => "title" -> v.asJson)
      ).flatten
    }
  }
  implicit val decoderSendButtonRequestSectionsInnerReply: Decoder[SendButtonRequestSectionsInnerReply] = Decoder.instance { c =>
    for {
      id <- c.downField("id").as[Option[String]]
      title <- c.downField("title").as[Option[String]]
    } yield SendButtonRequestSectionsInnerReply(
      id = id,
      title = title
    )
  }
}

