/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.onemsg.chat.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import io.onemsg.chat.model.ErrorResponse
import io.onemsg.chat.model.GetWebhook200Response

import com.squareup.moshi.Json

import io.onemsg.chat.infrastructure.ApiClient
import io.onemsg.chat.infrastructure.ApiResponse
import io.onemsg.chat.infrastructure.ClientException
import io.onemsg.chat.infrastructure.ClientError
import io.onemsg.chat.infrastructure.ServerException
import io.onemsg.chat.infrastructure.ServerError
import io.onemsg.chat.infrastructure.MultiValueMap
import io.onemsg.chat.infrastructure.PartConfig
import io.onemsg.chat.infrastructure.RequestConfig
import io.onemsg.chat.infrastructure.RequestMethod
import io.onemsg.chat.infrastructure.ResponseType
import io.onemsg.chat.infrastructure.Success
import io.onemsg.chat.infrastructure.toMultiValue

open class WebhooksApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.1msg.io")
        }
    }

    /**
     * GET /webhook
     * Get webhook URL
     * Returns the configured client webhook URL for this channel.
     * @param token JWT token or API key for authorization
     * @return GetWebhook200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getWebhook(token: kotlin.String) : GetWebhook200Response {
        val localVarResponse = getWebhookWithHttpInfo(token = token)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetWebhook200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /webhook
     * Get webhook URL
     * Returns the configured client webhook URL for this channel.
     * @param token JWT token or API key for authorization
     * @return ApiResponse<GetWebhook200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getWebhookWithHttpInfo(token: kotlin.String) : ApiResponse<GetWebhook200Response?> {
        val localVariableConfig = getWebhookRequestConfig(token = token)

        return request<Unit, GetWebhook200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getWebhook
     *
     * @param token JWT token or API key for authorization
     * @return RequestConfig
     */
    fun getWebhookRequestConfig(token: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("token", listOf(token.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/webhook",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /webhook
     * Set webhook URL
     * Configure the client webhook URL for inbound events.
     * @param token JWT token or API key for authorization
     * @param getWebhook200Response  (optional)
     * @return kotlin.collections.Map<kotlin.String, kotlin.Any>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun setWebhook(token: kotlin.String, getWebhook200Response: GetWebhook200Response? = null) : kotlin.collections.Map<kotlin.String, kotlin.Any> {
        val localVarResponse = setWebhookWithHttpInfo(token = token, getWebhook200Response = getWebhook200Response)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.Map<kotlin.String, kotlin.Any>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /webhook
     * Set webhook URL
     * Configure the client webhook URL for inbound events.
     * @param token JWT token or API key for authorization
     * @param getWebhook200Response  (optional)
     * @return ApiResponse<kotlin.collections.Map<kotlin.String, kotlin.Any>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun setWebhookWithHttpInfo(token: kotlin.String, getWebhook200Response: GetWebhook200Response?) : ApiResponse<kotlin.collections.Map<kotlin.String, kotlin.Any>?> {
        val localVariableConfig = setWebhookRequestConfig(token = token, getWebhook200Response = getWebhook200Response)

        return request<GetWebhook200Response, kotlin.collections.Map<kotlin.String, kotlin.Any>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation setWebhook
     *
     * @param token JWT token or API key for authorization
     * @param getWebhook200Response  (optional)
     * @return RequestConfig
     */
    fun setWebhookRequestConfig(token: kotlin.String, getWebhook200Response: GetWebhook200Response?) : RequestConfig<GetWebhook200Response> {
        val localVariableBody = getWebhook200Response
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("token", listOf(token.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/webhook",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
