/*
 * 1MSG WhatsApp Business API (Public)
 *
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OneMsg.ChatApi.Model;
using OneMsg.ChatApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OneMsg.ChatApi.Test.Model
{
    /// <summary>
    ///  Class for testing CreateReadMessage200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateReadMessage200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateReadMessage200Response
        //private CreateReadMessage200Response instance;

        public CreateReadMessage200ResponseTests()
        {
            // TODO uncomment below to create an instance of CreateReadMessage200Response
            //instance = new CreateReadMessage200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateReadMessage200Response
        /// </summary>
        [Fact]
        public void CreateReadMessage200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateReadMessage200Response
            //Assert.IsType<CreateReadMessage200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
    }
}
