/*
 * 1MSG WhatsApp Business API (Public)
 *
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OneMsg.ChatApi.Model;
using OneMsg.ChatApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OneMsg.ChatApi.Test.Model
{
    /// <summary>
    ///  Class for testing GetCommerce200ResponseInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetCommerce200ResponseInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetCommerce200ResponseInner
        //private GetCommerce200ResponseInner instance;

        public GetCommerce200ResponseInnerTests()
        {
            // TODO uncomment below to create an instance of GetCommerce200ResponseInner
            //instance = new GetCommerce200ResponseInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetCommerce200ResponseInner
        /// </summary>
        [Fact]
        public void GetCommerce200ResponseInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetCommerce200ResponseInner
            //Assert.IsType<GetCommerce200ResponseInner>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'IsCartEnabled'
        /// </summary>
        [Fact]
        public void IsCartEnabledTest()
        {
            // TODO unit test for the property 'IsCartEnabled'
        }

        /// <summary>
        /// Test the property 'IsCatalogVisible'
        /// </summary>
        [Fact]
        public void IsCatalogVisibleTest()
        {
            // TODO unit test for the property 'IsCatalogVisible'
        }
    }
}
