/*
 * 1MSG WhatsApp Business API (Public)
 *
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OneMsg.ChatApi.Model;
using OneMsg.ChatApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OneMsg.ChatApi.Test.Model
{
    /// <summary>
    ///  Class for testing SendFileRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendFileRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SendFileRequest
        //private SendFileRequest instance;

        public SendFileRequestTests()
        {
            // TODO uncomment below to create an instance of SendFileRequest
            //instance = new SendFileRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SendFileRequest
        /// </summary>
        [Fact]
        public void SendFileRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SendFileRequest
            //Assert.IsType<SendFileRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }

        /// <summary>
        /// Test the property 'MediaId'
        /// </summary>
        [Fact]
        public void MediaIdTest()
        {
            // TODO unit test for the property 'MediaId'
        }

        /// <summary>
        /// Test the property 'MediaType'
        /// </summary>
        [Fact]
        public void MediaTypeTest()
        {
            // TODO unit test for the property 'MediaType'
        }

        /// <summary>
        /// Test the property 'Voice'
        /// </summary>
        [Fact]
        public void VoiceTest()
        {
            // TODO unit test for the property 'Voice'
        }

        /// <summary>
        /// Test the property 'Caption'
        /// </summary>
        [Fact]
        public void CaptionTest()
        {
            // TODO unit test for the property 'Caption'
        }

        /// <summary>
        /// Test the property 'QuotedMsgId'
        /// </summary>
        [Fact]
        public void QuotedMsgIdTest()
        {
            // TODO unit test for the property 'QuotedMsgId'
        }

        /// <summary>
        /// Test the property 'ChatId'
        /// </summary>
        [Fact]
        public void ChatIdTest()
        {
            // TODO unit test for the property 'ChatId'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
    }
}
