/*
 * 1MSG WhatsApp Business API (Public)
 *
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OneMsg.Sdk.Model;
using OneMsg.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OneMsg.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SendOrderDetailsRequestLanguage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendOrderDetailsRequestLanguageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SendOrderDetailsRequestLanguage
        //private SendOrderDetailsRequestLanguage instance;

        public SendOrderDetailsRequestLanguageTests()
        {
            // TODO uncomment below to create an instance of SendOrderDetailsRequestLanguage
            //instance = new SendOrderDetailsRequestLanguage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SendOrderDetailsRequestLanguage
        /// </summary>
        [Fact]
        public void SendOrderDetailsRequestLanguageInstanceTest()
        {
            // TODO uncomment below to test "IsType" SendOrderDetailsRequestLanguage
            //Assert.IsType<SendOrderDetailsRequestLanguage>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Policy'
        /// </summary>
        [Fact]
        public void PolicyTest()
        {
            // TODO unit test for the property 'Policy'
        }
    }
}
