/*
 * 1MSG WhatsApp Business API (Public)
 *
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OneMsg.Sdk.Model;
using OneMsg.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OneMsg.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SendOrderDetailsRequestOrder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendOrderDetailsRequestOrderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SendOrderDetailsRequestOrder
        //private SendOrderDetailsRequestOrder instance;

        public SendOrderDetailsRequestOrderTests()
        {
            // TODO uncomment below to create an instance of SendOrderDetailsRequestOrder
            //instance = new SendOrderDetailsRequestOrder();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SendOrderDetailsRequestOrder
        /// </summary>
        [Fact]
        public void SendOrderDetailsRequestOrderInstanceTest()
        {
            // TODO uncomment below to test "IsType" SendOrderDetailsRequestOrder
            //Assert.IsType<SendOrderDetailsRequestOrder>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'Subtotal'
        /// </summary>
        [Fact]
        public void SubtotalTest()
        {
            // TODO unit test for the property 'Subtotal'
        }

        /// <summary>
        /// Test the property 'Tax'
        /// </summary>
        [Fact]
        public void TaxTest()
        {
            // TODO unit test for the property 'Tax'
        }

        /// <summary>
        /// Test the property 'Shipping'
        /// </summary>
        [Fact]
        public void ShippingTest()
        {
            // TODO unit test for the property 'Shipping'
        }

        /// <summary>
        /// Test the property 'Discount'
        /// </summary>
        [Fact]
        public void DiscountTest()
        {
            // TODO unit test for the property 'Discount'
        }
    }
}
