/*
 * 1MSG WhatsApp Business API (Public)
 *
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OneMsg.Sdk.Model;
using OneMsg.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OneMsg.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateCallingSettings200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateCallingSettings200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateCallingSettings200Response
        //private UpdateCallingSettings200Response instance;

        public UpdateCallingSettings200ResponseTests()
        {
            // TODO uncomment below to create an instance of UpdateCallingSettings200Response
            //instance = new UpdateCallingSettings200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateCallingSettings200Response
        /// </summary>
        [Fact]
        public void UpdateCallingSettings200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateCallingSettings200Response
            //Assert.IsType<UpdateCallingSettings200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }

        /// <summary>
        /// Test the property 'Response'
        /// </summary>
        [Fact]
        public void ResponseTest()
        {
            // TODO unit test for the property 'Response'
        }
    }
}
