/*
 * 1MSG WhatsApp Business API (Public)
 *
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using OneMsg.ChatApi.Client;
using OneMsg.ChatApi.Model;

namespace OneMsg.ChatApi.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITemplatesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create message template
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="addTemplateRequest"> (optional)</param>
        /// <returns>Dictionary&lt;string, Object&gt;</returns>
        Dictionary<string, Object> AddTemplate(string token, AddTemplateRequest addTemplateRequest = default);

        /// <summary>
        /// Create message template
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="addTemplateRequest"> (optional)</param>
        /// <returns>ApiResponse of Dictionary&lt;string, Object&gt;</returns>
        ApiResponse<Dictionary<string, Object>> AddTemplateWithHttpInfo(string token, AddTemplateRequest addTemplateRequest = default);
        /// <summary>
        /// Get templates list
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <returns>ListTemplates200Response</returns>
        ListTemplates200Response ListTemplates(string token);

        /// <summary>
        /// Get templates list
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <returns>ApiResponse of ListTemplates200Response</returns>
        ApiResponse<ListTemplates200Response> ListTemplatesWithHttpInfo(string token);
        /// <summary>
        /// Remove message template
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="requestBody"> (optional)</param>
        /// <returns>Dictionary&lt;string, Object&gt;</returns>
        Dictionary<string, Object> RemoveTemplate(string token, Dictionary<string, Object> requestBody = default);

        /// <summary>
        /// Remove message template
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="requestBody"> (optional)</param>
        /// <returns>ApiResponse of Dictionary&lt;string, Object&gt;</returns>
        ApiResponse<Dictionary<string, Object>> RemoveTemplateWithHttpInfo(string token, Dictionary<string, Object> requestBody = default);
        /// <summary>
        /// Send Template Message
        /// </summary>
        /// <remarks>
        /// Send a WhatsApp template message (works outside the 24-hour session window).  Supported &#x60;params&#x60; button &#x60;sub_type&#x60; values include: &#x60;url&#x60;, &#x60;quick_reply&#x60;, &#x60;copy_code&#x60; / &#x60;coupon_code&#x60;, &#x60;catalog&#x60;, &#x60;flow&#x60;, &#x60;limited_time_offer&#x60;, and **&#x60;order_details&#x60;** (WhatsApp Payments **India only** — requires an approved Utility template with an ORDER_DETAILS button).  For India order/invoice payments outside 24h, include a button component:  &#x60;&#x60;&#x60;json {   \&quot;type\&quot;: \&quot;button\&quot;,   \&quot;sub_type\&quot;: \&quot;order_details\&quot;,   \&quot;index\&quot;: 0,   \&quot;parameters\&quot;: [{     \&quot;type\&quot;: \&quot;action\&quot;,     \&quot;action\&quot;: { \&quot;order_details\&quot;: { \&quot;reference_id\&quot;: \&quot;...\&quot;, \&quot;currency\&quot;: \&quot;INR\&quot;, \&quot;order\&quot;: {} } }   }] } &#x60;&#x60;&#x60;  Convenience wrapper with structured fields: &#x60;POST /sendOrderDetails&#x60;. 
        /// </remarks>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="sendTemplateRequest"> (optional)</param>
        /// <returns>Dictionary&lt;string, Object&gt;</returns>
        Dictionary<string, Object> SendTemplate(string token, SendTemplateRequest sendTemplateRequest = default);

        /// <summary>
        /// Send Template Message
        /// </summary>
        /// <remarks>
        /// Send a WhatsApp template message (works outside the 24-hour session window).  Supported &#x60;params&#x60; button &#x60;sub_type&#x60; values include: &#x60;url&#x60;, &#x60;quick_reply&#x60;, &#x60;copy_code&#x60; / &#x60;coupon_code&#x60;, &#x60;catalog&#x60;, &#x60;flow&#x60;, &#x60;limited_time_offer&#x60;, and **&#x60;order_details&#x60;** (WhatsApp Payments **India only** — requires an approved Utility template with an ORDER_DETAILS button).  For India order/invoice payments outside 24h, include a button component:  &#x60;&#x60;&#x60;json {   \&quot;type\&quot;: \&quot;button\&quot;,   \&quot;sub_type\&quot;: \&quot;order_details\&quot;,   \&quot;index\&quot;: 0,   \&quot;parameters\&quot;: [{     \&quot;type\&quot;: \&quot;action\&quot;,     \&quot;action\&quot;: { \&quot;order_details\&quot;: { \&quot;reference_id\&quot;: \&quot;...\&quot;, \&quot;currency\&quot;: \&quot;INR\&quot;, \&quot;order\&quot;: {} } }   }] } &#x60;&#x60;&#x60;  Convenience wrapper with structured fields: &#x60;POST /sendOrderDetails&#x60;. 
        /// </remarks>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="sendTemplateRequest"> (optional)</param>
        /// <returns>ApiResponse of Dictionary&lt;string, Object&gt;</returns>
        ApiResponse<Dictionary<string, Object>> SendTemplateWithHttpInfo(string token, SendTemplateRequest sendTemplateRequest = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITemplatesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create message template
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="addTemplateRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Object&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, Object>> AddTemplateAsync(string token, AddTemplateRequest addTemplateRequest = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create message template
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="addTemplateRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Object&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, Object>>> AddTemplateWithHttpInfoAsync(string token, AddTemplateRequest addTemplateRequest = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get templates list
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListTemplates200Response</returns>
        System.Threading.Tasks.Task<ListTemplates200Response> ListTemplatesAsync(string token, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get templates list
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListTemplates200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListTemplates200Response>> ListTemplatesWithHttpInfoAsync(string token, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Remove message template
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="requestBody"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Object&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, Object>> RemoveTemplateAsync(string token, Dictionary<string, Object> requestBody = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Remove message template
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="requestBody"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Object&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, Object>>> RemoveTemplateWithHttpInfoAsync(string token, Dictionary<string, Object> requestBody = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Send Template Message
        /// </summary>
        /// <remarks>
        /// Send a WhatsApp template message (works outside the 24-hour session window).  Supported &#x60;params&#x60; button &#x60;sub_type&#x60; values include: &#x60;url&#x60;, &#x60;quick_reply&#x60;, &#x60;copy_code&#x60; / &#x60;coupon_code&#x60;, &#x60;catalog&#x60;, &#x60;flow&#x60;, &#x60;limited_time_offer&#x60;, and **&#x60;order_details&#x60;** (WhatsApp Payments **India only** — requires an approved Utility template with an ORDER_DETAILS button).  For India order/invoice payments outside 24h, include a button component:  &#x60;&#x60;&#x60;json {   \&quot;type\&quot;: \&quot;button\&quot;,   \&quot;sub_type\&quot;: \&quot;order_details\&quot;,   \&quot;index\&quot;: 0,   \&quot;parameters\&quot;: [{     \&quot;type\&quot;: \&quot;action\&quot;,     \&quot;action\&quot;: { \&quot;order_details\&quot;: { \&quot;reference_id\&quot;: \&quot;...\&quot;, \&quot;currency\&quot;: \&quot;INR\&quot;, \&quot;order\&quot;: {} } }   }] } &#x60;&#x60;&#x60;  Convenience wrapper with structured fields: &#x60;POST /sendOrderDetails&#x60;. 
        /// </remarks>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="sendTemplateRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Object&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, Object>> SendTemplateAsync(string token, SendTemplateRequest sendTemplateRequest = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Send Template Message
        /// </summary>
        /// <remarks>
        /// Send a WhatsApp template message (works outside the 24-hour session window).  Supported &#x60;params&#x60; button &#x60;sub_type&#x60; values include: &#x60;url&#x60;, &#x60;quick_reply&#x60;, &#x60;copy_code&#x60; / &#x60;coupon_code&#x60;, &#x60;catalog&#x60;, &#x60;flow&#x60;, &#x60;limited_time_offer&#x60;, and **&#x60;order_details&#x60;** (WhatsApp Payments **India only** — requires an approved Utility template with an ORDER_DETAILS button).  For India order/invoice payments outside 24h, include a button component:  &#x60;&#x60;&#x60;json {   \&quot;type\&quot;: \&quot;button\&quot;,   \&quot;sub_type\&quot;: \&quot;order_details\&quot;,   \&quot;index\&quot;: 0,   \&quot;parameters\&quot;: [{     \&quot;type\&quot;: \&quot;action\&quot;,     \&quot;action\&quot;: { \&quot;order_details\&quot;: { \&quot;reference_id\&quot;: \&quot;...\&quot;, \&quot;currency\&quot;: \&quot;INR\&quot;, \&quot;order\&quot;: {} } }   }] } &#x60;&#x60;&#x60;  Convenience wrapper with structured fields: &#x60;POST /sendOrderDetails&#x60;. 
        /// </remarks>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="sendTemplateRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Object&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, Object>>> SendTemplateWithHttpInfoAsync(string token, SendTemplateRequest sendTemplateRequest = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITemplatesApi : ITemplatesApiSync, ITemplatesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TemplatesApi : IDisposable, ITemplatesApi
    {
        private OneMsg.ChatApi.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TemplatesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public TemplatesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TemplatesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public TemplatesApi(string basePath)
        {
            this.Configuration = OneMsg.ChatApi.Client.Configuration.MergeConfigurations(
                OneMsg.ChatApi.Client.GlobalConfiguration.Instance,
                new OneMsg.ChatApi.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new OneMsg.ChatApi.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = OneMsg.ChatApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TemplatesApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public TemplatesApi(OneMsg.ChatApi.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = OneMsg.ChatApi.Client.Configuration.MergeConfigurations(
                OneMsg.ChatApi.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new OneMsg.ChatApi.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = OneMsg.ChatApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TemplatesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public TemplatesApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TemplatesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public TemplatesApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = OneMsg.ChatApi.Client.Configuration.MergeConfigurations(
                OneMsg.ChatApi.Client.GlobalConfiguration.Instance,
                new OneMsg.ChatApi.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new OneMsg.ChatApi.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = OneMsg.ChatApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TemplatesApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public TemplatesApi(HttpClient client, OneMsg.ChatApi.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = OneMsg.ChatApi.Client.Configuration.MergeConfigurations(
                OneMsg.ChatApi.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new OneMsg.ChatApi.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = OneMsg.ChatApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TemplatesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public TemplatesApi(OneMsg.ChatApi.Client.ISynchronousClient client, OneMsg.ChatApi.Client.IAsynchronousClient asyncClient, OneMsg.ChatApi.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = OneMsg.ChatApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public OneMsg.ChatApi.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public OneMsg.ChatApi.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public OneMsg.ChatApi.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public OneMsg.ChatApi.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public OneMsg.ChatApi.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create message template 
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="addTemplateRequest"> (optional)</param>
        /// <returns>Dictionary&lt;string, Object&gt;</returns>
        public Dictionary<string, Object> AddTemplate(string token, AddTemplateRequest addTemplateRequest = default)
        {
            OneMsg.ChatApi.Client.ApiResponse<Dictionary<string, Object>> localVarResponse = AddTemplateWithHttpInfo(token, addTemplateRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create message template 
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="addTemplateRequest"> (optional)</param>
        /// <returns>ApiResponse of Dictionary&lt;string, Object&gt;</returns>
        public OneMsg.ChatApi.Client.ApiResponse<Dictionary<string, Object>> AddTemplateWithHttpInfo(string token, AddTemplateRequest addTemplateRequest = default)
        {
            // verify the required parameter 'token' is set
            if (token == null)
                throw new OneMsg.ChatApi.Client.ApiException(400, "Missing required parameter 'token' when calling TemplatesApi->AddTemplate");

            OneMsg.ChatApi.Client.RequestOptions localVarRequestOptions = new OneMsg.ChatApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = OneMsg.ChatApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OneMsg.ChatApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(OneMsg.ChatApi.Client.ClientUtils.ParameterToMultiMap("", "token", token));
            localVarRequestOptions.Data = addTemplateRequest;

            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarRequestOptions.QueryParameters.Add(OneMsg.ChatApi.Client.ClientUtils.ParameterToMultiMap("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Dictionary<string, Object>>("/addTemplate", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AddTemplate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create message template 
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="addTemplateRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Object&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, Object>> AddTemplateAsync(string token, AddTemplateRequest addTemplateRequest = default, System.Threading.CancellationToken cancellationToken = default)
        {
            OneMsg.ChatApi.Client.ApiResponse<Dictionary<string, Object>> localVarResponse = await AddTemplateWithHttpInfoAsync(token, addTemplateRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create message template 
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="addTemplateRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Object&gt;)</returns>
        public async System.Threading.Tasks.Task<OneMsg.ChatApi.Client.ApiResponse<Dictionary<string, Object>>> AddTemplateWithHttpInfoAsync(string token, AddTemplateRequest addTemplateRequest = default, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'token' is set
            if (token == null)
                throw new OneMsg.ChatApi.Client.ApiException(400, "Missing required parameter 'token' when calling TemplatesApi->AddTemplate");


            OneMsg.ChatApi.Client.RequestOptions localVarRequestOptions = new OneMsg.ChatApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = OneMsg.ChatApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OneMsg.ChatApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(OneMsg.ChatApi.Client.ClientUtils.ParameterToMultiMap("", "token", token));
            localVarRequestOptions.Data = addTemplateRequest;

            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarRequestOptions.QueryParameters.Add(OneMsg.ChatApi.Client.ClientUtils.ParameterToMultiMap("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Dictionary<string, Object>>("/addTemplate", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AddTemplate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get templates list 
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <returns>ListTemplates200Response</returns>
        public ListTemplates200Response ListTemplates(string token)
        {
            OneMsg.ChatApi.Client.ApiResponse<ListTemplates200Response> localVarResponse = ListTemplatesWithHttpInfo(token);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get templates list 
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <returns>ApiResponse of ListTemplates200Response</returns>
        public OneMsg.ChatApi.Client.ApiResponse<ListTemplates200Response> ListTemplatesWithHttpInfo(string token)
        {
            // verify the required parameter 'token' is set
            if (token == null)
                throw new OneMsg.ChatApi.Client.ApiException(400, "Missing required parameter 'token' when calling TemplatesApi->ListTemplates");

            OneMsg.ChatApi.Client.RequestOptions localVarRequestOptions = new OneMsg.ChatApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = OneMsg.ChatApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OneMsg.ChatApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(OneMsg.ChatApi.Client.ClientUtils.ParameterToMultiMap("", "token", token));

            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarRequestOptions.QueryParameters.Add(OneMsg.ChatApi.Client.ClientUtils.ParameterToMultiMap("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListTemplates200Response>("/templates", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListTemplates", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get templates list 
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListTemplates200Response</returns>
        public async System.Threading.Tasks.Task<ListTemplates200Response> ListTemplatesAsync(string token, System.Threading.CancellationToken cancellationToken = default)
        {
            OneMsg.ChatApi.Client.ApiResponse<ListTemplates200Response> localVarResponse = await ListTemplatesWithHttpInfoAsync(token, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get templates list 
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListTemplates200Response)</returns>
        public async System.Threading.Tasks.Task<OneMsg.ChatApi.Client.ApiResponse<ListTemplates200Response>> ListTemplatesWithHttpInfoAsync(string token, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'token' is set
            if (token == null)
                throw new OneMsg.ChatApi.Client.ApiException(400, "Missing required parameter 'token' when calling TemplatesApi->ListTemplates");


            OneMsg.ChatApi.Client.RequestOptions localVarRequestOptions = new OneMsg.ChatApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = OneMsg.ChatApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OneMsg.ChatApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(OneMsg.ChatApi.Client.ClientUtils.ParameterToMultiMap("", "token", token));

            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarRequestOptions.QueryParameters.Add(OneMsg.ChatApi.Client.ClientUtils.ParameterToMultiMap("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListTemplates200Response>("/templates", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListTemplates", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Remove message template 
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="requestBody"> (optional)</param>
        /// <returns>Dictionary&lt;string, Object&gt;</returns>
        public Dictionary<string, Object> RemoveTemplate(string token, Dictionary<string, Object> requestBody = default)
        {
            OneMsg.ChatApi.Client.ApiResponse<Dictionary<string, Object>> localVarResponse = RemoveTemplateWithHttpInfo(token, requestBody);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Remove message template 
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="requestBody"> (optional)</param>
        /// <returns>ApiResponse of Dictionary&lt;string, Object&gt;</returns>
        public OneMsg.ChatApi.Client.ApiResponse<Dictionary<string, Object>> RemoveTemplateWithHttpInfo(string token, Dictionary<string, Object> requestBody = default)
        {
            // verify the required parameter 'token' is set
            if (token == null)
                throw new OneMsg.ChatApi.Client.ApiException(400, "Missing required parameter 'token' when calling TemplatesApi->RemoveTemplate");

            OneMsg.ChatApi.Client.RequestOptions localVarRequestOptions = new OneMsg.ChatApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = OneMsg.ChatApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OneMsg.ChatApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(OneMsg.ChatApi.Client.ClientUtils.ParameterToMultiMap("", "token", token));
            localVarRequestOptions.Data = requestBody;

            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarRequestOptions.QueryParameters.Add(OneMsg.ChatApi.Client.ClientUtils.ParameterToMultiMap("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Dictionary<string, Object>>("/removeTemplate", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RemoveTemplate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Remove message template 
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="requestBody"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Object&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, Object>> RemoveTemplateAsync(string token, Dictionary<string, Object> requestBody = default, System.Threading.CancellationToken cancellationToken = default)
        {
            OneMsg.ChatApi.Client.ApiResponse<Dictionary<string, Object>> localVarResponse = await RemoveTemplateWithHttpInfoAsync(token, requestBody, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Remove message template 
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="requestBody"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Object&gt;)</returns>
        public async System.Threading.Tasks.Task<OneMsg.ChatApi.Client.ApiResponse<Dictionary<string, Object>>> RemoveTemplateWithHttpInfoAsync(string token, Dictionary<string, Object> requestBody = default, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'token' is set
            if (token == null)
                throw new OneMsg.ChatApi.Client.ApiException(400, "Missing required parameter 'token' when calling TemplatesApi->RemoveTemplate");


            OneMsg.ChatApi.Client.RequestOptions localVarRequestOptions = new OneMsg.ChatApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = OneMsg.ChatApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OneMsg.ChatApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(OneMsg.ChatApi.Client.ClientUtils.ParameterToMultiMap("", "token", token));
            localVarRequestOptions.Data = requestBody;

            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarRequestOptions.QueryParameters.Add(OneMsg.ChatApi.Client.ClientUtils.ParameterToMultiMap("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Dictionary<string, Object>>("/removeTemplate", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RemoveTemplate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Send Template Message Send a WhatsApp template message (works outside the 24-hour session window).  Supported &#x60;params&#x60; button &#x60;sub_type&#x60; values include: &#x60;url&#x60;, &#x60;quick_reply&#x60;, &#x60;copy_code&#x60; / &#x60;coupon_code&#x60;, &#x60;catalog&#x60;, &#x60;flow&#x60;, &#x60;limited_time_offer&#x60;, and **&#x60;order_details&#x60;** (WhatsApp Payments **India only** — requires an approved Utility template with an ORDER_DETAILS button).  For India order/invoice payments outside 24h, include a button component:  &#x60;&#x60;&#x60;json {   \&quot;type\&quot;: \&quot;button\&quot;,   \&quot;sub_type\&quot;: \&quot;order_details\&quot;,   \&quot;index\&quot;: 0,   \&quot;parameters\&quot;: [{     \&quot;type\&quot;: \&quot;action\&quot;,     \&quot;action\&quot;: { \&quot;order_details\&quot;: { \&quot;reference_id\&quot;: \&quot;...\&quot;, \&quot;currency\&quot;: \&quot;INR\&quot;, \&quot;order\&quot;: {} } }   }] } &#x60;&#x60;&#x60;  Convenience wrapper with structured fields: &#x60;POST /sendOrderDetails&#x60;. 
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="sendTemplateRequest"> (optional)</param>
        /// <returns>Dictionary&lt;string, Object&gt;</returns>
        public Dictionary<string, Object> SendTemplate(string token, SendTemplateRequest sendTemplateRequest = default)
        {
            OneMsg.ChatApi.Client.ApiResponse<Dictionary<string, Object>> localVarResponse = SendTemplateWithHttpInfo(token, sendTemplateRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Send Template Message Send a WhatsApp template message (works outside the 24-hour session window).  Supported &#x60;params&#x60; button &#x60;sub_type&#x60; values include: &#x60;url&#x60;, &#x60;quick_reply&#x60;, &#x60;copy_code&#x60; / &#x60;coupon_code&#x60;, &#x60;catalog&#x60;, &#x60;flow&#x60;, &#x60;limited_time_offer&#x60;, and **&#x60;order_details&#x60;** (WhatsApp Payments **India only** — requires an approved Utility template with an ORDER_DETAILS button).  For India order/invoice payments outside 24h, include a button component:  &#x60;&#x60;&#x60;json {   \&quot;type\&quot;: \&quot;button\&quot;,   \&quot;sub_type\&quot;: \&quot;order_details\&quot;,   \&quot;index\&quot;: 0,   \&quot;parameters\&quot;: [{     \&quot;type\&quot;: \&quot;action\&quot;,     \&quot;action\&quot;: { \&quot;order_details\&quot;: { \&quot;reference_id\&quot;: \&quot;...\&quot;, \&quot;currency\&quot;: \&quot;INR\&quot;, \&quot;order\&quot;: {} } }   }] } &#x60;&#x60;&#x60;  Convenience wrapper with structured fields: &#x60;POST /sendOrderDetails&#x60;. 
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="sendTemplateRequest"> (optional)</param>
        /// <returns>ApiResponse of Dictionary&lt;string, Object&gt;</returns>
        public OneMsg.ChatApi.Client.ApiResponse<Dictionary<string, Object>> SendTemplateWithHttpInfo(string token, SendTemplateRequest sendTemplateRequest = default)
        {
            // verify the required parameter 'token' is set
            if (token == null)
                throw new OneMsg.ChatApi.Client.ApiException(400, "Missing required parameter 'token' when calling TemplatesApi->SendTemplate");

            OneMsg.ChatApi.Client.RequestOptions localVarRequestOptions = new OneMsg.ChatApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = OneMsg.ChatApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OneMsg.ChatApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(OneMsg.ChatApi.Client.ClientUtils.ParameterToMultiMap("", "token", token));
            localVarRequestOptions.Data = sendTemplateRequest;

            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarRequestOptions.QueryParameters.Add(OneMsg.ChatApi.Client.ClientUtils.ParameterToMultiMap("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Dictionary<string, Object>>("/sendTemplate", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SendTemplate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Send Template Message Send a WhatsApp template message (works outside the 24-hour session window).  Supported &#x60;params&#x60; button &#x60;sub_type&#x60; values include: &#x60;url&#x60;, &#x60;quick_reply&#x60;, &#x60;copy_code&#x60; / &#x60;coupon_code&#x60;, &#x60;catalog&#x60;, &#x60;flow&#x60;, &#x60;limited_time_offer&#x60;, and **&#x60;order_details&#x60;** (WhatsApp Payments **India only** — requires an approved Utility template with an ORDER_DETAILS button).  For India order/invoice payments outside 24h, include a button component:  &#x60;&#x60;&#x60;json {   \&quot;type\&quot;: \&quot;button\&quot;,   \&quot;sub_type\&quot;: \&quot;order_details\&quot;,   \&quot;index\&quot;: 0,   \&quot;parameters\&quot;: [{     \&quot;type\&quot;: \&quot;action\&quot;,     \&quot;action\&quot;: { \&quot;order_details\&quot;: { \&quot;reference_id\&quot;: \&quot;...\&quot;, \&quot;currency\&quot;: \&quot;INR\&quot;, \&quot;order\&quot;: {} } }   }] } &#x60;&#x60;&#x60;  Convenience wrapper with structured fields: &#x60;POST /sendOrderDetails&#x60;. 
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="sendTemplateRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Dictionary&lt;string, Object&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, Object>> SendTemplateAsync(string token, SendTemplateRequest sendTemplateRequest = default, System.Threading.CancellationToken cancellationToken = default)
        {
            OneMsg.ChatApi.Client.ApiResponse<Dictionary<string, Object>> localVarResponse = await SendTemplateWithHttpInfoAsync(token, sendTemplateRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Send Template Message Send a WhatsApp template message (works outside the 24-hour session window).  Supported &#x60;params&#x60; button &#x60;sub_type&#x60; values include: &#x60;url&#x60;, &#x60;quick_reply&#x60;, &#x60;copy_code&#x60; / &#x60;coupon_code&#x60;, &#x60;catalog&#x60;, &#x60;flow&#x60;, &#x60;limited_time_offer&#x60;, and **&#x60;order_details&#x60;** (WhatsApp Payments **India only** — requires an approved Utility template with an ORDER_DETAILS button).  For India order/invoice payments outside 24h, include a button component:  &#x60;&#x60;&#x60;json {   \&quot;type\&quot;: \&quot;button\&quot;,   \&quot;sub_type\&quot;: \&quot;order_details\&quot;,   \&quot;index\&quot;: 0,   \&quot;parameters\&quot;: [{     \&quot;type\&quot;: \&quot;action\&quot;,     \&quot;action\&quot;: { \&quot;order_details\&quot;: { \&quot;reference_id\&quot;: \&quot;...\&quot;, \&quot;currency\&quot;: \&quot;INR\&quot;, \&quot;order\&quot;: {} } }   }] } &#x60;&#x60;&#x60;  Convenience wrapper with structured fields: &#x60;POST /sendOrderDetails&#x60;. 
        /// </summary>
        /// <exception cref="OneMsg.ChatApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">JWT token or API key for authorization</param>
        /// <param name="sendTemplateRequest"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Object&gt;)</returns>
        public async System.Threading.Tasks.Task<OneMsg.ChatApi.Client.ApiResponse<Dictionary<string, Object>>> SendTemplateWithHttpInfoAsync(string token, SendTemplateRequest sendTemplateRequest = default, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'token' is set
            if (token == null)
                throw new OneMsg.ChatApi.Client.ApiException(400, "Missing required parameter 'token' when calling TemplatesApi->SendTemplate");


            OneMsg.ChatApi.Client.RequestOptions localVarRequestOptions = new OneMsg.ChatApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = OneMsg.ChatApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = OneMsg.ChatApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(OneMsg.ChatApi.Client.ClientUtils.ParameterToMultiMap("", "token", token));
            localVarRequestOptions.Data = sendTemplateRequest;

            // authentication (tokenAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("token")))
            {
                localVarRequestOptions.QueryParameters.Add(OneMsg.ChatApi.Client.ClientUtils.ParameterToMultiMap("", "token", this.Configuration.GetApiKeyWithPrefix("token")));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Dictionary<string, Object>>("/sendTemplate", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SendTemplate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
