/*
 * 1MSG WhatsApp Business API (Public)
 *
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = OneMsg.ChatApi.Client.FileParameter;
using OpenAPIDateConverter = OneMsg.ChatApi.Client.OpenAPIDateConverter;

namespace OneMsg.ChatApi.Model
{
    /// <summary>
    /// CreateReadMessageRequest
    /// </summary>
    [DataContract(Name = "createReadMessage_request")]
    public partial class CreateReadMessageRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateReadMessageRequest" /> class.
        /// </summary>
        /// <param name="messageId">messageId.</param>
        /// <param name="msgId">msgId.</param>
        /// <param name="typingIndicator">Show WhatsApp typing indicator (max 25s or until reply) (default to false).</param>
        public CreateReadMessageRequest(string messageId = default, string msgId = default, bool typingIndicator = false)
        {
            this.MessageId = messageId;
            this.MsgId = msgId;
            this.TypingIndicator = typingIndicator;
        }

        /// <summary>
        /// Gets or Sets MessageId
        /// </summary>
        [DataMember(Name = "messageId", EmitDefaultValue = false)]
        public string MessageId { get; set; }

        /// <summary>
        /// Gets or Sets MsgId
        /// </summary>
        [DataMember(Name = "msgId", EmitDefaultValue = false)]
        public string MsgId { get; set; }

        /// <summary>
        /// Show WhatsApp typing indicator (max 25s or until reply)
        /// </summary>
        /// <value>Show WhatsApp typing indicator (max 25s or until reply)</value>
        [DataMember(Name = "typingIndicator", EmitDefaultValue = true)]
        public bool TypingIndicator { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateReadMessageRequest {\n");
            sb.Append("  MessageId: ").Append(MessageId).Append("\n");
            sb.Append("  MsgId: ").Append(MsgId).Append("\n");
            sb.Append("  TypingIndicator: ").Append(TypingIndicator).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
