/*
 * 1MSG WhatsApp Business API (Public)
 *
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = OneMsg.ChatApi.Client.FileParameter;
using OpenAPIDateConverter = OneMsg.ChatApi.Client.OpenAPIDateConverter;

namespace OneMsg.ChatApi.Model
{
    /// <summary>
    /// SendCtaUrlRequest
    /// </summary>
    [DataContract(Name = "sendCtaUrl_request")]
    public partial class SendCtaUrlRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendCtaUrlRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SendCtaUrlRequest()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendCtaUrlRequest" /> class.
        /// </summary>
        /// <param name="phone">phone.</param>
        /// <param name="chatId">chatId.</param>
        /// <param name="body">body (required).</param>
        /// <param name="displayText">Button label (required).</param>
        /// <param name="url">url (required).</param>
        /// <param name="header">header.</param>
        /// <param name="footer">footer.</param>
        /// <param name="quotedMsgId">quotedMsgId.</param>
        public SendCtaUrlRequest(int phone = default, string chatId = default, string body = default, string displayText = default, string url = default, Dictionary<string, Object> header = default, string footer = default, string quotedMsgId = default)
        {
            // to ensure "body" is required (not null)
            if (body == null)
            {
                throw new ArgumentNullException("body is a required property for SendCtaUrlRequest and cannot be null");
            }
            this.Body = body;
            // to ensure "displayText" is required (not null)
            if (displayText == null)
            {
                throw new ArgumentNullException("displayText is a required property for SendCtaUrlRequest and cannot be null");
            }
            this.DisplayText = displayText;
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for SendCtaUrlRequest and cannot be null");
            }
            this.Url = url;
            this.Phone = phone;
            this.ChatId = chatId;
            this.Header = header;
            this.Footer = footer;
            this.QuotedMsgId = quotedMsgId;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets Phone
        /// </summary>
        [DataMember(Name = "phone", EmitDefaultValue = false)]
        public int Phone { get; set; }

        /// <summary>
        /// Gets or Sets ChatId
        /// </summary>
        [DataMember(Name = "chatId", EmitDefaultValue = false)]
        public string ChatId { get; set; }

        /// <summary>
        /// Gets or Sets Body
        /// </summary>
        [DataMember(Name = "body", IsRequired = true, EmitDefaultValue = true)]
        public string Body { get; set; }

        /// <summary>
        /// Button label
        /// </summary>
        /// <value>Button label</value>
        [DataMember(Name = "displayText", IsRequired = true, EmitDefaultValue = true)]
        public string DisplayText { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets Header
        /// </summary>
        [DataMember(Name = "header", EmitDefaultValue = false)]
        public Dictionary<string, Object> Header { get; set; }

        /// <summary>
        /// Gets or Sets Footer
        /// </summary>
        [DataMember(Name = "footer", EmitDefaultValue = false)]
        public string Footer { get; set; }

        /// <summary>
        /// Gets or Sets QuotedMsgId
        /// </summary>
        [DataMember(Name = "quotedMsgId", EmitDefaultValue = false)]
        public string QuotedMsgId { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendCtaUrlRequest {\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  ChatId: ").Append(ChatId).Append("\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  DisplayText: ").Append(DisplayText).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Header: ").Append(Header).Append("\n");
            sb.Append("  Footer: ").Append(Footer).Append("\n");
            sb.Append("  QuotedMsgId: ").Append(QuotedMsgId).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
