/*
 * 1MSG WhatsApp Business API (Public)
 *
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CallingSettingsCallingSipServersInner {
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    #[serde(rename = "request_uri_user_params", skip_serializing_if = "Option::is_none")]
    pub request_uri_user_params: Option<std::collections::HashMap<String, String>>,
    /// Present on GET when SIP credentials are returned by Meta
    #[serde(rename = "sip_user_password", skip_serializing_if = "Option::is_none")]
    pub sip_user_password: Option<String>,
    /// Alternate password field name from some Meta responses
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "app_id", skip_serializing_if = "Option::is_none")]
    pub app_id: Option<String>,
}

impl CallingSettingsCallingSipServersInner {
    pub fn new() -> CallingSettingsCallingSipServersInner {
        CallingSettingsCallingSipServersInner {
            hostname: None,
            port: None,
            request_uri_user_params: None,
            sip_user_password: None,
            password: None,
            app_id: None,
        }
    }
}

