/*
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.onemsg.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateReadMessageRequest
 */
class CreateReadMessageRequestTest {
    private final CreateReadMessageRequest model = new CreateReadMessageRequest();

    /**
     * Model tests for CreateReadMessageRequest
     */
    @Test
    void testCreateReadMessageRequest() {
        // TODO: test CreateReadMessageRequest
    }

    /**
     * Test the property 'messageId'
     */
    @Test
    void messageIdTest() {
        // TODO: test messageId
    }

    /**
     * Test the property 'msgId'
     */
    @Test
    void msgIdTest() {
        // TODO: test msgId
    }

    /**
     * Test the property 'typingIndicator'
     */
    @Test
    void typingIndicatorTest() {
        // TODO: test typingIndicator
    }

}
