/*
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.onemsg.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SendOrderDetailsRequest
 */
class SendOrderDetailsRequestTest {
    private final SendOrderDetailsRequest model = new SendOrderDetailsRequest();

    /**
     * Model tests for SendOrderDetailsRequest
     */
    @Test
    void testSendOrderDetailsRequest() {
        // TODO: test SendOrderDetailsRequest
    }

    /**
     * Test the property 'phone'
     */
    @Test
    void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'chatId'
     */
    @Test
    void chatIdTest() {
        // TODO: test chatId
    }

    /**
     * Test the property 'template'
     */
    @Test
    void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'language'
     */
    @Test
    void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'params'
     */
    @Test
    void paramsTest() {
        // TODO: test params
    }

    /**
     * Test the property 'order'
     */
    @Test
    void orderTest() {
        // TODO: test order
    }

    /**
     * Test the property 'referenceId'
     */
    @Test
    void referenceIdTest() {
        // TODO: test referenceId
    }

    /**
     * Test the property 'paymentSettings'
     */
    @Test
    void paymentSettingsTest() {
        // TODO: test paymentSettings
    }

    /**
     * Test the property 'currency'
     */
    @Test
    void currencyTest() {
        // TODO: test currency
    }

}
