[package]
name = "one-msg-sdk"
version = "2.0.1"
authors = ["support@1msg.io"]
description = "Official Rust SDK for the 1MSG WhatsApp Business API"
license = "MIT"
edition = "2021"
repository = "https://github.com/1msg/1msg-sdk"
homepage = "https://1msg.io"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_with = { version = "^3.8", default-features = false, features = ["base64", "std", "macros"] }
serde_json = "^1.0"
serde_repr = "^0.1"
url = "^2.5"
reqwest = { version = "^0.13", default-features = false, features = ["json", "multipart", "query", "form"] }

[features]
default = ["native-tls"]
native-tls = ["reqwest/native-tls"]
rustls = ["reqwest/rustls"]
