/**
 * 1MSG WhatsApp Business API (Public)
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.onemsg.sdk.core

import io.onemsg.sdk.model._
import io.circe.{Decoder, Encoder}
import sttp.client3.circe.SttpCirceApi

object JsonSupport extends SttpCirceApi with DateSerializers with AdditionalTypeSerializers {

  implicit val CallingSettingsCallingStatusDecoder: Decoder[CallingSettingsCallingEnums.Status] = Decoder.decodeEnumeration(CallingSettingsCallingEnums.Status)
  implicit val CallingSettingsCallingStatusEncoder: Encoder[CallingSettingsCallingEnums.Status] = Encoder.encodeEnumeration(CallingSettingsCallingEnums.Status)
  implicit val CallingSettingsCallingCallIconVisibilityDecoder: Decoder[CallingSettingsCallingEnums.CallIconVisibility] = Decoder.decodeEnumeration(CallingSettingsCallingEnums.CallIconVisibility)
  implicit val CallingSettingsCallingCallIconVisibilityEncoder: Encoder[CallingSettingsCallingEnums.CallIconVisibility] = Encoder.encodeEnumeration(CallingSettingsCallingEnums.CallIconVisibility)
  implicit val CallingSettingsCallingCallbackPermissionStatusDecoder: Decoder[CallingSettingsCallingEnums.CallbackPermissionStatus] = Decoder.decodeEnumeration(CallingSettingsCallingEnums.CallbackPermissionStatus)
  implicit val CallingSettingsCallingCallbackPermissionStatusEncoder: Encoder[CallingSettingsCallingEnums.CallbackPermissionStatus] = Encoder.encodeEnumeration(CallingSettingsCallingEnums.CallbackPermissionStatus)
  implicit val CallingSettingsCallingSrtpKeyExchangeProtocolDecoder: Decoder[CallingSettingsCallingEnums.SrtpKeyExchangeProtocol] = Decoder.decodeEnumeration(CallingSettingsCallingEnums.SrtpKeyExchangeProtocol)
  implicit val CallingSettingsCallingSrtpKeyExchangeProtocolEncoder: Encoder[CallingSettingsCallingEnums.SrtpKeyExchangeProtocol] = Encoder.encodeEnumeration(CallingSettingsCallingEnums.SrtpKeyExchangeProtocol)
  implicit val CallingSettingsCallingSipStatusDecoder: Decoder[CallingSettingsCallingSipEnums.Status] = Decoder.decodeEnumeration(CallingSettingsCallingSipEnums.Status)
  implicit val CallingSettingsCallingSipStatusEncoder: Encoder[CallingSettingsCallingSipEnums.Status] = Encoder.encodeEnumeration(CallingSettingsCallingSipEnums.Status)
  implicit val CallingSettingsCallingVideoStatusDecoder: Decoder[CallingSettingsCallingVideoEnums.Status] = Decoder.decodeEnumeration(CallingSettingsCallingVideoEnums.Status)
  implicit val CallingSettingsCallingVideoStatusEncoder: Encoder[CallingSettingsCallingVideoEnums.Status] = Encoder.encodeEnumeration(CallingSettingsCallingVideoEnums.Status)
  implicit val GetWhatsappBusinessEncryption200ResponseBusinessPublicKeySignatureStatusDecoder: Decoder[GetWhatsappBusinessEncryption200ResponseEnums.BusinessPublicKeySignatureStatus] = Decoder.decodeEnumeration(GetWhatsappBusinessEncryption200ResponseEnums.BusinessPublicKeySignatureStatus)
  implicit val GetWhatsappBusinessEncryption200ResponseBusinessPublicKeySignatureStatusEncoder: Encoder[GetWhatsappBusinessEncryption200ResponseEnums.BusinessPublicKeySignatureStatus] = Encoder.encodeEnumeration(GetWhatsappBusinessEncryption200ResponseEnums.BusinessPublicKeySignatureStatus)
  implicit val InitiateCallRequestMessagingProductDecoder: Decoder[InitiateCallRequestEnums.MessagingProduct] = Decoder.decodeEnumeration(InitiateCallRequestEnums.MessagingProduct)
  implicit val InitiateCallRequestMessagingProductEncoder: Encoder[InitiateCallRequestEnums.MessagingProduct] = Encoder.encodeEnumeration(InitiateCallRequestEnums.MessagingProduct)
  implicit val InitiateCallRequestActionDecoder: Decoder[InitiateCallRequestEnums.Action] = Decoder.decodeEnumeration(InitiateCallRequestEnums.Action)
  implicit val InitiateCallRequestActionEncoder: Encoder[InitiateCallRequestEnums.Action] = Encoder.encodeEnumeration(InitiateCallRequestEnums.Action)
  implicit val InitiateCallRequestSessionSdpTypeDecoder: Decoder[InitiateCallRequestSessionEnums.SdpType] = Decoder.decodeEnumeration(InitiateCallRequestSessionEnums.SdpType)
  implicit val InitiateCallRequestSessionSdpTypeEncoder: Encoder[InitiateCallRequestSessionEnums.SdpType] = Encoder.encodeEnumeration(InitiateCallRequestSessionEnums.SdpType)
  implicit val ProfileInfoVerticalDecoder: Decoder[ProfileInfoEnums.Vertical] = Decoder.decodeEnumeration(ProfileInfoEnums.Vertical)
  implicit val ProfileInfoVerticalEncoder: Encoder[ProfileInfoEnums.Vertical] = Encoder.encodeEnumeration(ProfileInfoEnums.Vertical)
  implicit val SendAddressMessageRequestCountryDecoder: Decoder[SendAddressMessageRequestEnums.Country] = Decoder.decodeEnumeration(SendAddressMessageRequestEnums.Country)
  implicit val SendAddressMessageRequestCountryEncoder: Encoder[SendAddressMessageRequestEnums.Country] = Encoder.encodeEnumeration(SendAddressMessageRequestEnums.Country)
  implicit val SendFileRequestMediaTypeDecoder: Decoder[SendFileRequestEnums.MediaType] = Decoder.decodeEnumeration(SendFileRequestEnums.MediaType)
  implicit val SendFileRequestMediaTypeEncoder: Encoder[SendFileRequestEnums.MediaType] = Encoder.encodeEnumeration(SendFileRequestEnums.MediaType)
  implicit val SendFlowRequest1FlowActionDecoder: Decoder[SendFlowRequest1Enums.FlowAction] = Decoder.decodeEnumeration(SendFlowRequest1Enums.FlowAction)
  implicit val SendFlowRequest1FlowActionEncoder: Encoder[SendFlowRequest1Enums.FlowAction] = Encoder.encodeEnumeration(SendFlowRequest1Enums.FlowAction)
  implicit val SendFlowRequest1ModeDecoder: Decoder[SendFlowRequest1Enums.Mode] = Decoder.decodeEnumeration(SendFlowRequest1Enums.Mode)
  implicit val SendFlowRequest1ModeEncoder: Encoder[SendFlowRequest1Enums.Mode] = Encoder.encodeEnumeration(SendFlowRequest1Enums.Mode)
  implicit val SendPaymentRequestRequestRegionDecoder: Decoder[SendPaymentRequestRequestEnums.Region] = Decoder.decodeEnumeration(SendPaymentRequestRequestEnums.Region)
  implicit val SendPaymentRequestRequestRegionEncoder: Encoder[SendPaymentRequestRequestEnums.Region] = Encoder.encodeEnumeration(SendPaymentRequestRequestEnums.Region)
}
