package io.onemsg.chat.core

import io.circe.Json
import io.circe.syntax._

/** Helpers for form-urlencoded bodies generated by scala-sttp. */
object FormSupport {
  def fromMap(entries: (String, Any)*): Map[String, String] =
    entries.flatMap {
      case (_, null)  => None
      case (_, None)  => None
      case (k, Some(v)) => Some(k -> stringify(v))
      case (k, v)     => Some(k -> stringify(v))
    }.toMap

  private def stringify(value: Any): String =
    value match {
      case j: Json                                        => j.noSpaces
      case s: String                                      => s
      case h: io.onemsg.chat.model.SendFlowRequestHeader  => h.value.noSpaces
      case h: io.onemsg.chat.model.SendFlowRequest1Header => h.value.noSpaces
      case other                                          => other.toString
    }

  def jsonSeq(values: Seq[Json]): String =
    values.asJson.noSpaces
}
