/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.onemsg.chat.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Response for successfully sent message
 *
 * @param sent Whether the message was successfully queued for sending
 * @param id Message ID
 * @param message Status message
 * @param description Detailed description
 */


data class MessageSentResponse (

    /* Whether the message was successfully queued for sending */
    @Json(name = "sent")
    val sent: kotlin.Boolean? = null,

    /* Message ID */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Status message */
    @Json(name = "message")
    val message: kotlin.String? = null,

    /* Detailed description */
    @Json(name = "description")
    val description: kotlin.String? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

