/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.onemsg.chat.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param phone 
 * @param chatId 
 * @param mediaId WABA media id from uploadMedia
 * @param link Public URL to webp sticker
 * @param quotedMsgId 
 */


data class SendStickerRequest (

    @Json(name = "phone")
    val phone: kotlin.Int? = null,

    @Json(name = "chatId")
    val chatId: kotlin.String? = null,

    /* WABA media id from uploadMedia */
    @Json(name = "mediaId")
    val mediaId: kotlin.String? = null,

    /* Public URL to webp sticker */
    @Json(name = "link")
    val link: kotlin.String? = null,

    @Json(name = "quotedMsgId")
    val quotedMsgId: kotlin.String? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

