/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.onemsg.chat.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.onemsg.chat.api.WebhooksApi
import io.onemsg.chat.model.ErrorResponse
import io.onemsg.chat.model.GetWebhook200Response

class WebhooksApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WebhooksApi
        //val apiInstance = WebhooksApi()

        // to test getWebhook
        should("test getWebhook") {
            // uncomment below to test getWebhook
            //val token : kotlin.String = token_example // kotlin.String | JWT token or API key for authorization
            //val result : GetWebhook200Response = apiInstance.getWebhook(token)
            //result shouldBe ("TODO")
        }

        // to test setWebhook
        should("test setWebhook") {
            // uncomment below to test setWebhook
            //val token : kotlin.String = token_example // kotlin.String | JWT token or API key for authorization
            //val getWebhook200Response : GetWebhook200Response =  // GetWebhook200Response | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.setWebhook(token, getWebhook200Response)
            //result shouldBe ("TODO")
        }

    }
}
