# coding: utf-8

"""
    1MSG WhatsApp Business API (Public)

    Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 

    The version of the OpenAPI document: 1.0.0
    Contact: support@1msg.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SendAddressMessageRequest(BaseModel):
    """
    SendAddressMessageRequest
    """ # noqa: E501
    phone: Optional[StrictInt] = Field(default=None, description="Recipient phone (E.164 digits, no +). Must match country.")
    chat_id: Optional[StrictStr] = Field(default=None, alias="chatId")
    body: StrictStr = Field(description="Body text shown with the address request")
    country: Optional[StrictStr] = Field(default=None, description="Address form country. Defaults to IN if omitted.")
    values: Optional[Dict[str, Any]] = Field(default=None, description="Optional prefilled address fields")
    saved_addresses: Optional[List[Dict[str, Any]]] = Field(default=None, description="Optional previously saved addresses for the user")
    validation_errors: Optional[Dict[str, Any]] = Field(default=None, description="Optional field validation errors when re-prompting")
    quoted_msg_id: Optional[StrictStr] = Field(default=None, alias="quotedMsgId")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["phone", "chatId", "body", "country", "values", "saved_addresses", "validation_errors", "quotedMsgId"]

    @field_validator('country')
    def country_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['IN', 'SG']):
            raise ValueError("must be one of enum values ('IN', 'SG')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendAddressMessageRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendAddressMessageRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "phone": obj.get("phone"),
            "chatId": obj.get("chatId"),
            "body": obj.get("body"),
            "country": obj.get("country"),
            "values": obj.get("values"),
            "saved_addresses": obj.get("saved_addresses"),
            "validation_errors": obj.get("validation_errors"),
            "quotedMsgId": obj.get("quotedMsgId")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


