/*
 * 1MSG WhatsApp Business API (Public)
 *
 * Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@1msg.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = OneMsg.Sdk.Client.FileParameter;
using OpenAPIDateConverter = OneMsg.Sdk.Client.OpenAPIDateConverter;

namespace OneMsg.Sdk.Model
{
    /// <summary>
    /// SendAddressMessageRequest
    /// </summary>
    [DataContract(Name = "sendAddressMessage_request")]
    public partial class SendAddressMessageRequest : IValidatableObject
    {
        /// <summary>
        /// Address form country. Defaults to IN if omitted.
        /// </summary>
        /// <value>Address form country. Defaults to IN if omitted.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CountryEnum
        {
            /// <summary>
            /// Enum IN for value: IN
            /// </summary>
            [EnumMember(Value = "IN")]
            IN = 1,

            /// <summary>
            /// Enum SG for value: SG
            /// </summary>
            [EnumMember(Value = "SG")]
            SG = 2
        }


        /// <summary>
        /// Address form country. Defaults to IN if omitted.
        /// </summary>
        /// <value>Address form country. Defaults to IN if omitted.</value>
        /*
        <example>SG</example>
        */
        [DataMember(Name = "country", EmitDefaultValue = false)]
        public CountryEnum? Country { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendAddressMessageRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SendAddressMessageRequest()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendAddressMessageRequest" /> class.
        /// </summary>
        /// <param name="phone">Recipient phone (E.164 digits, no +). Must match country..</param>
        /// <param name="chatId">chatId.</param>
        /// <param name="body">Body text shown with the address request (required).</param>
        /// <param name="country">Address form country. Defaults to IN if omitted..</param>
        /// <param name="values">Optional prefilled address fields.</param>
        /// <param name="savedAddresses">Optional previously saved addresses for the user.</param>
        /// <param name="validationErrors">Optional field validation errors when re-prompting.</param>
        /// <param name="quotedMsgId">quotedMsgId.</param>
        public SendAddressMessageRequest(int phone = default, string chatId = default, string body = default, CountryEnum? country = default, Dictionary<string, Object> values = default, List<Dictionary<string, Object>> savedAddresses = default, Dictionary<string, Object> validationErrors = default, string quotedMsgId = default)
        {
            // to ensure "body" is required (not null)
            if (body == null)
            {
                throw new ArgumentNullException("body is a required property for SendAddressMessageRequest and cannot be null");
            }
            this.Body = body;
            this.Phone = phone;
            this.ChatId = chatId;
            this.Country = country;
            this.Values = values;
            this.SavedAddresses = savedAddresses;
            this.ValidationErrors = validationErrors;
            this.QuotedMsgId = quotedMsgId;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Recipient phone (E.164 digits, no +). Must match country.
        /// </summary>
        /// <value>Recipient phone (E.164 digits, no +). Must match country.</value>
        [DataMember(Name = "phone", EmitDefaultValue = false)]
        public int Phone { get; set; }

        /// <summary>
        /// Gets or Sets ChatId
        /// </summary>
        [DataMember(Name = "chatId", EmitDefaultValue = false)]
        public string ChatId { get; set; }

        /// <summary>
        /// Body text shown with the address request
        /// </summary>
        /// <value>Body text shown with the address request</value>
        [DataMember(Name = "body", IsRequired = true, EmitDefaultValue = true)]
        public string Body { get; set; }

        /// <summary>
        /// Optional prefilled address fields
        /// </summary>
        /// <value>Optional prefilled address fields</value>
        [DataMember(Name = "values", EmitDefaultValue = false)]
        public Dictionary<string, Object> Values { get; set; }

        /// <summary>
        /// Optional previously saved addresses for the user
        /// </summary>
        /// <value>Optional previously saved addresses for the user</value>
        [DataMember(Name = "saved_addresses", EmitDefaultValue = false)]
        public List<Dictionary<string, Object>> SavedAddresses { get; set; }

        /// <summary>
        /// Optional field validation errors when re-prompting
        /// </summary>
        /// <value>Optional field validation errors when re-prompting</value>
        [DataMember(Name = "validation_errors", EmitDefaultValue = false)]
        public Dictionary<string, Object> ValidationErrors { get; set; }

        /// <summary>
        /// Gets or Sets QuotedMsgId
        /// </summary>
        [DataMember(Name = "quotedMsgId", EmitDefaultValue = false)]
        public string QuotedMsgId { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendAddressMessageRequest {\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  ChatId: ").Append(ChatId).Append("\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Values: ").Append(Values).Append("\n");
            sb.Append("  SavedAddresses: ").Append(SavedAddresses).Append("\n");
            sb.Append("  ValidationErrors: ").Append(ValidationErrors).Append("\n");
            sb.Append("  QuotedMsgId: ").Append(QuotedMsgId).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
