=begin
#1MSG WhatsApp Business API (Public)

#Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 

The version of the OpenAPI document: 1.0.0
Contact: support@1msg.io
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module OneMsgSdk
  class CreateCommerceRequestParams < ApiModelBase
    # Enable cart
    attr_accessor :is_cart_enabled

    # Show catalog storefront icon
    attr_accessor :is_catalog_visible

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'is_cart_enabled' => :'is_cart_enabled',
        :'is_catalog_visible' => :'is_catalog_visible'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'is_cart_enabled' => :'Boolean',
        :'is_catalog_visible' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OneMsgSdk::CreateCommerceRequestParams` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OneMsgSdk::CreateCommerceRequestParams`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'is_cart_enabled')
        self.is_cart_enabled = attributes[:'is_cart_enabled']
      else
        self.is_cart_enabled = nil
      end

      if attributes.key?(:'is_catalog_visible')
        self.is_catalog_visible = attributes[:'is_catalog_visible']
      else
        self.is_catalog_visible = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @is_cart_enabled.nil?
        invalid_properties.push('invalid value for "is_cart_enabled", is_cart_enabled cannot be nil.')
      end

      if @is_catalog_visible.nil?
        invalid_properties.push('invalid value for "is_catalog_visible", is_catalog_visible cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @is_cart_enabled.nil?
      return false if @is_catalog_visible.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] is_cart_enabled Value to be assigned
    def is_cart_enabled=(is_cart_enabled)
      if is_cart_enabled.nil?
        fail ArgumentError, 'is_cart_enabled cannot be nil'
      end

      @is_cart_enabled = is_cart_enabled
    end

    # Custom attribute writer method with validation
    # @param [Object] is_catalog_visible Value to be assigned
    def is_catalog_visible=(is_catalog_visible)
      if is_catalog_visible.nil?
        fail ArgumentError, 'is_catalog_visible cannot be nil'
      end

      @is_catalog_visible = is_catalog_visible
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          is_cart_enabled == o.is_cart_enabled &&
          is_catalog_visible == o.is_catalog_visible
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [is_cart_enabled, is_catalog_visible].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
