=begin
#1MSG WhatsApp Business API (Public)

#Public client API for sending messages, managing groups, flows, and templates.  This is the API exposed to end customers via platform.1msg.io  **Authentication:** All requests require `token` query parameter with JWT or API key.  **Documentation:** https://help.1msg.io/platform-1msg/getting-start/quick-start **API Docs:** https://docs.1msg.io/ 

The version of the OpenAPI document: 1.0.0
Contact: support@1msg.io
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module OneMsgSdk
  # Request body for sending a text message
  class SendMessageRequest < ApiModelBase
    # Message text, UTF-8 or UTF-16 string with emoji
    attr_accessor :body

    # Message ID to quote/reply to (Cloud API wamid)
    attr_accessor :quoted_msg_id

    # Chat ID in format: phone@c.us (individual) or phone@g.us (group)
    attr_accessor :chat_id

    # Phone number starting with country code (alternative to chatId)
    attr_accessor :phone

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'body' => :'body',
        :'quoted_msg_id' => :'quotedMsgId',
        :'chat_id' => :'chatId',
        :'phone' => :'phone'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'body' => :'String',
        :'quoted_msg_id' => :'String',
        :'chat_id' => :'String',
        :'phone' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OneMsgSdk::SendMessageRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OneMsgSdk::SendMessageRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'body')
        self.body = attributes[:'body']
      else
        self.body = nil
      end

      if attributes.key?(:'quoted_msg_id')
        self.quoted_msg_id = attributes[:'quoted_msg_id']
      end

      if attributes.key?(:'chat_id')
        self.chat_id = attributes[:'chat_id']
      end

      if attributes.key?(:'phone')
        self.phone = attributes[:'phone']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @body.nil?
        invalid_properties.push('invalid value for "body", body cannot be nil.')
      end

      if @body.to_s.length > 4096
        invalid_properties.push('invalid value for "body", the character length must be smaller than or equal to 4096.')
      end

      if @body.to_s.length < 1
        invalid_properties.push('invalid value for "body", the character length must be greater than or equal to 1.')
      end

      pattern = Regexp.new(/^wamid\..+$/)
      if !@quoted_msg_id.nil? && @quoted_msg_id !~ pattern
        invalid_properties.push("invalid value for \"quoted_msg_id\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^[0-9]+@[cg]\.us$/)
      if !@chat_id.nil? && @chat_id !~ pattern
        invalid_properties.push("invalid value for \"chat_id\", must conform to the pattern #{pattern}.")
      end

      if !@phone.nil? && @phone > 999999999999999
        invalid_properties.push('invalid value for "phone", must be smaller than or equal to 999999999999999.')
      end

      if !@phone.nil? && @phone < 1000000000
        invalid_properties.push('invalid value for "phone", must be greater than or equal to 1000000000.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @body.nil?
      return false if @body.to_s.length > 4096
      return false if @body.to_s.length < 1
      return false if !@quoted_msg_id.nil? && @quoted_msg_id !~ Regexp.new(/^wamid\..+$/)
      return false if !@chat_id.nil? && @chat_id !~ Regexp.new(/^[0-9]+@[cg]\.us$/)
      return false if !@phone.nil? && @phone > 999999999999999
      return false if !@phone.nil? && @phone < 1000000000
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] body Value to be assigned
    def body=(body)
      if body.nil?
        fail ArgumentError, 'body cannot be nil'
      end

      if body.to_s.length > 4096
        fail ArgumentError, 'invalid value for "body", the character length must be smaller than or equal to 4096.'
      end

      if body.to_s.length < 1
        fail ArgumentError, 'invalid value for "body", the character length must be greater than or equal to 1.'
      end

      @body = body
    end

    # Custom attribute writer method with validation
    # @param [Object] quoted_msg_id Value to be assigned
    def quoted_msg_id=(quoted_msg_id)
      if quoted_msg_id.nil?
        fail ArgumentError, 'quoted_msg_id cannot be nil'
      end

      pattern = Regexp.new(/^wamid\..+$/)
      if quoted_msg_id !~ pattern
        fail ArgumentError, "invalid value for \"quoted_msg_id\", must conform to the pattern #{pattern}."
      end

      @quoted_msg_id = quoted_msg_id
    end

    # Custom attribute writer method with validation
    # @param [Object] chat_id Value to be assigned
    def chat_id=(chat_id)
      if chat_id.nil?
        fail ArgumentError, 'chat_id cannot be nil'
      end

      pattern = Regexp.new(/^[0-9]+@[cg]\.us$/)
      if chat_id !~ pattern
        fail ArgumentError, "invalid value for \"chat_id\", must conform to the pattern #{pattern}."
      end

      @chat_id = chat_id
    end

    # Custom attribute writer method with validation
    # @param [Object] phone Value to be assigned
    def phone=(phone)
      if phone.nil?
        fail ArgumentError, 'phone cannot be nil'
      end

      if phone > 999999999999999
        fail ArgumentError, 'invalid value for "phone", must be smaller than or equal to 999999999999999.'
      end

      if phone < 1000000000
        fail ArgumentError, 'invalid value for "phone", must be greater than or equal to 1000000000.'
      end

      @phone = phone
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          body == o.body &&
          quoted_msg_id == o.quoted_msg_id &&
          chat_id == o.chat_id &&
          phone == o.phone
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [body, quoted_msg_id, chat_id, phone].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
