/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.onemsg.chat.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.onemsg.chat.model.SendStickerRequest

class SendStickerRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SendStickerRequest
        //val modelInstance = SendStickerRequest()

        // to test the property `phone`
        should("test phone") {
            // uncomment below to test the property
            //modelInstance.phone shouldBe ("TODO")
        }

        // to test the property `chatId`
        should("test chatId") {
            // uncomment below to test the property
            //modelInstance.chatId shouldBe ("TODO")
        }

        // to test the property `mediaId` - WABA media id from uploadMedia
        should("test mediaId") {
            // uncomment below to test the property
            //modelInstance.mediaId shouldBe ("TODO")
        }

        // to test the property `link` - Public URL to webp sticker
        should("test link") {
            // uncomment below to test the property
            //modelInstance.link shouldBe ("TODO")
        }

        // to test the property `quotedMsgId`
        should("test quotedMsgId") {
            // uncomment below to test the property
            //modelInstance.quotedMsgId shouldBe ("TODO")
        }

    }
}
