/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.onemsg.chat.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.onemsg.chat.model.SendTemplateRequestLanguage

class SendTemplateRequestLanguageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SendTemplateRequestLanguage
        //val modelInstance = SendTemplateRequestLanguage()

        // to test the property `policy`
        should("test policy") {
            // uncomment below to test the property
            //modelInstance.policy shouldBe ("TODO")
        }

        // to test the property `code`
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

    }
}
